/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package backgroundtask provides a shared lifecycle registry for long-running
// executions (sub-agents, shell commands, ...) that may outlive the tool call
// that launched them.
//
// The central type is Manager: a non-generic, in-memory registry that tracks
// foreground/background/auto-background runs and exposes them via Get/List/
// Cancel/WaitAllDone. Manager is deliberately non-generic so a single instance
// can be shared across heterogeneous domains (e.g. agent runs and shell runs)
// under one unified task-ID space.
//
// What a run actually does is supplied per-call as a WorkFunc passed to Run, which
// keeps the engine agnostic to what it runs (agents, shell, ...); adapters that
// produce WorkFunc values live in the consuming packages (subagent, filesystem).
// Completed task output can optionally be persisted through OutputStore.
//
// Manager tracks lifecycle only. Streaming a specific run's events in real time
// is intentionally out of scope here: the launcher (a domain adapter) already
// knows the concrete event type, so live streaming, if needed, belongs at that
// typed layer rather than behind a type-erased registry-wide channel.
package backgroundtask

import (
	"context"
	"fmt"
	"io"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/cloudwego/eino/adk/filesystem"
	"github.com/cloudwego/eino/internal"
	"github.com/cloudwego/eino/schema"
)

// Status represents the lifecycle status of a task.
type Status string

const (
	// StatusRunning indicates the task is currently executing.
	StatusRunning Status = "running"
	// StatusCompleted indicates the task finished successfully.
	StatusCompleted Status = "completed"
	// StatusFailed indicates the task terminated with an error.
	StatusFailed Status = "failed"
	// StatusCanceled indicates the task was stopped by an external request
	// (Cancel / Close) via context cancellation.
	StatusCanceled Status = "canceled"
)

// Task represents a single managed execution record.
type Task struct {
	// ID is the unique identifier for this task, generated by Manager.
	ID string
	// Type is a caller-supplied tag (e.g. "bash", "subagent") identifying what kind
	// of work this task runs. The Manager does not interpret it; it lets the
	// ShouldAutoBackground hook and observers distinguish domains without parsing
	// Description. Empty if the launcher did not set it.
	Type string
	// ToolUseID is the id of the tool call that launched this task, when known.
	// It lets a host correlate a terminal notification back to the originating
	// tool call. Empty if the launcher did not set it.
	ToolUseID string
	// Description is a human-readable summary of what the task does.
	Description string
	// Status is the current lifecycle status.
	Status Status
	// Result contains the task output, set when Status is StatusCompleted.
	Result string
	// OutputFile is the path the task's result was persisted to, when an output
	// store is configured (see Config.OutputStore). Empty otherwise. The file
	// outlives the in-memory record, so it remains readable after the Manager is
	// rebuilt.
	OutputFile string
	// Error contains the error message, set when Status is StatusFailed.
	Error string
	// RunInBackground indicates whether this task is running (or ran) in the
	// background — either launched with RunInBackground, or moved to the background
	// after exhausting its foreground budget. It distinguishes background tasks
	// from foreground ones when inspecting task state, and gates terminal
	// notifications (see Subscribe).
	RunInBackground bool
	// ResultQueried indicates whether the orchestrating agent has queried this
	// task's result (typically via the task_output tool). This helps developers
	// know which background task results have already been consumed.
	ResultQueried bool
	// CreatedAt is the time the task was registered.
	CreatedAt time.Time
	// DoneAt is the time the task reached a terminal state. Nil if still running.
	DoneAt *time.Time
	// Metadata holds arbitrary extensible fields for future use.
	Metadata map[string]any
}

// RunResult is the return value of Run.
// It reports the outcome of a run so the caller does not need to track the task itself.
type RunResult struct {
	// TaskID is the unique identifier assigned to this execution.
	TaskID string
	// Status indicates the outcome: StatusCompleted, StatusFailed, or StatusRunning (for background tasks).
	Status Status
	// Result is the run output when Status is StatusCompleted.
	Result string
	// OutputFile is the path the run's output is (or will be) persisted to, when an
	// output store is configured. It is reserved at launch, so it is populated even
	// for a StatusRunning result — letting the caller hand the agent a path to read
	// once the task completes. Empty when no output store is configured.
	OutputFile string
	// Error is the error message when Status is StatusFailed.
	Error string
}

// Notification reports a background task's transition to a terminal state
// (completed or failed; an explicitly canceled task does not notify). It carries a
// snapshot of the task at that moment — not a live event stream: streaming a run's
// domain events is intentionally out of scope (see the package doc).
//
// Notifications are delivered only for tasks that ran in the background (launched
// with RunInBackground, or auto-backgrounded after their foreground budget).
// Foreground runs return their result to the caller inline and never notify.
type Notification struct {
	// Task is the task's state at the terminal transition.
	Task *Task
}

// RunInput is the execution-agnostic input for Run.
// Domain-specific parameters (which agent, which command, the prompt) are
// captured by the WorkFunc closure, not here.
type RunInput struct {
	// Description is a short human-readable title for the task, stored in Task.Description.
	Description string
	// Type is an optional tag for the task (e.g. "bash", "subagent"), stored in
	// Task.Type. See Task.Type.
	Type string
	// ToolUseID is the optional id of the tool call launching this task, stored in
	// Task.ToolUseID. See Task.ToolUseID.
	ToolUseID string
	// RunInBackground controls execution mode: true returns immediately with StatusRunning.
	RunInBackground bool
	// Metadata is optional caller-supplied data attached to the task's Task.Metadata.
	// It is for observers (Get/List, the task_output tool, the host) to correlate or
	// label background tasks — e.g. an originating tool-call ID, session, or trace.
	// The Manager does not interpret it. It is shallow-copied into the task on creation.
	Metadata map[string]any
	// ForegroundTimeoutMs optionally overrides the Manager's foreground budget for
	// this run only. When nil, the Manager's configured default applies. When non-nil,
	// it bounds how long the run may occupy the foreground before its deadline fires
	// (see Config.ShouldAutoBackground for what happens at the deadline). A value <= 0
	// removes the deadline for this run (blocks until completion). Ignored when
	// RunInBackground is true.
	ForegroundTimeoutMs *int
}

// defaultForegroundTimeoutMs is the default foreground budget (120 seconds).
const defaultForegroundTimeoutMs = 120_000

// Config configures a Manager.
type Config struct {
	// ForegroundTimeoutMs sets the foreground budget: the time a foreground run is
	// allowed to occupy the foreground before its deadline fires.
	// When > 0, a foreground run that hasn't completed within this many
	// milliseconds reaches its deadline (see ShouldAutoBackground for what happens then).
	// When 0, there is no deadline (foreground runs block until completion).
	//
	// Default: 120000ms (120 seconds).
	ForegroundTimeoutMs *int

	// ShouldAutoBackground decides, at a foreground run's deadline, whether it may be
	// moved to the background (kept running) instead of being canceled. Applications
	// can use it to permit long-lived workloads such as servers and watchers while
	// timing out commands whose results are no longer useful. For shell commands,
	// filesystem.IsAutoBackgroundAllowed provides a ready reference implementation.
	//
	// It is consulted ONLY for the auto path — a foreground run that hits its
	// deadline. An explicit RunInBackground run always backgrounds immediately,
	// regardless of this hook.
	//
	// When nil (the default), it is treated as always returning false: a run that
	// hits its deadline is canceled and reported as timed out, never auto-backgrounded.
	ShouldAutoBackground func(ctx context.Context, task *Task) bool

	// OutputStore, when set together with OutputDir, persists each completed task's
	// result to a file at OutputDir/<taskID>.output and records the path in
	// Task.OutputFile. The file outlives the in-memory record, so a task's output
	// remains readable (by path) even after the Manager is rebuilt. Writes are
	// best-effort: a write failure does not fail the task. A filesystem.Backend
	// satisfies this interface directly.
	OutputStore OutputStore

	// OutputDir is the directory under which task output files are written. Only
	// used when OutputStore is set.
	OutputDir string
}

// OutputStore persists task output to a durable location. A filesystem.Backend
// satisfies this interface directly; any other durable store can implement the
// single Write method.
type OutputStore interface {
	// Write creates or overwrites the file at req.FilePath with req.Content.
	Write(ctx context.Context, req *filesystem.WriteRequest) error
}

// Manager is a non-generic, in-memory registry that owns the lifecycle of
// managed executions: creation, foreground/background/auto-background
// switching, cancellation and terminal-state tracking.
//
// It is intentionally execution-agnostic: it does not know whether a task is an
// agent or a shell command. Callers launch work via the free function Run,
// passing a WorkFunc that performs the actual execution. A single Manager can
// therefore be shared across multiple domains under one task-ID space.
type Manager struct {
	mu                   sync.Mutex
	cond                 *sync.Cond
	tasks                map[string]*taskRecord
	seq                  int64
	lastMs               int64
	closed               bool
	foregroundTimeoutMs  int
	shouldAutoBackground func(ctx context.Context, task *Task) bool
	outputStore          OutputStore
	outputDir            string

	// Subscription state, initialized lazily by Subscribe.
	subscribeOnce sync.Once
	notifyCh      chan *Notification
	notifyBuf     *internal.UnboundedChan[*Notification]
}

type taskRecord struct {
	task   Task
	cancel context.CancelFunc // cancels the run's context
	done   bool               // true once task reaches a terminal state
}

// New creates a new Manager.
// By default, the foreground budget is 120 seconds; set Config.ForegroundTimeoutMs
// to 0 to remove the deadline (foreground runs block until completion). What
// happens when the budget is reached is governed by Config.ShouldAutoBackground
// (default: cancel the run and report it timed out).
func New(_ context.Context, conf *Config) *Manager {
	m := &Manager{
		tasks:               make(map[string]*taskRecord),
		foregroundTimeoutMs: defaultForegroundTimeoutMs,
	}
	m.cond = sync.NewCond(&m.mu)
	if conf != nil && conf.ForegroundTimeoutMs != nil {
		m.foregroundTimeoutMs = *conf.ForegroundTimeoutMs
	}
	if conf != nil {
		m.shouldAutoBackground = conf.ShouldAutoBackground
		m.outputStore = conf.OutputStore
		m.outputDir = conf.OutputDir
	}
	return m
}

// allowAutoBackground reports whether a run that has hit its foreground deadline
// may be moved to the background. With no configured hook, the answer is false.
func (m *Manager) allowAutoBackground(ctx context.Context, task *Task) bool {
	if m.shouldAutoBackground == nil {
		return false
	}
	return m.shouldAutoBackground(ctx, task)
}

// Get returns the current state of a task by ID.
// Returns (nil, false) if the task does not exist.
func (m *Manager) Get(id string) (*Task, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return nil, false
	}
	return cloneTask(&rec.task), true
}

// WaitForTask blocks until the task with the given id reaches a terminal state, or
// until ctx is canceled, and returns its current state. It returns (nil, false) if
// no such task exists. If ctx is canceled before the task finishes, it returns the
// task's latest (still-running) snapshot with ok=true — callers should inspect
// Task.DoneAt / Task.Status to tell whether the wait actually completed.
func (m *Manager) WaitForTask(ctx context.Context, id string) (*Task, bool) {
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			m.cond.Broadcast()
		case <-done:
		}
	}()

	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return nil, false
	}
	for !rec.done {
		if ctx.Err() != nil {
			break
		}
		m.cond.Wait()
	}
	return cloneTask(&rec.task), true
}

// MarkQueried marks a task's result as having been queried by the orchestrating
// agent (typically via the task_output tool). This helps developers know which
// background task results have already been consumed.
func (m *Manager) MarkQueried(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.task.ResultQueried = true
	}
}

// List returns a snapshot of all tasks (both running and completed).
func (m *Manager) List() []*Task {
	m.mu.Lock()
	defer m.mu.Unlock()

	tasks := make([]*Task, 0, len(m.tasks))
	for _, rec := range m.tasks {
		tasks = append(tasks, cloneTask(&rec.task))
	}
	return tasks
}

// Cancel stops a running task. The run's context is canceled and the task
// transitions to StatusCanceled.
// Returns an error if the task does not exist or is not running.
func (m *Manager) Cancel(id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return fmt.Errorf("no background task has id %q, so there is nothing to stop. "+
			"If you are unsure of the id, there is nothing left to cancel", id)
	}
	if rec.done {
		return fmt.Errorf("background task %q has already finished (status: %s) and cannot be stopped. "+
			"Use the task_output tool with this id to read its result instead", id, rec.task.Status)
	}

	m.cancelTask(rec)
	return nil
}

// Subscribe returns a channel that receives a Notification each time a background
// task reaches a terminal state. It is the hook a host uses to surface completions
// to the agent (e.g. by injecting a task-notification message).
//
// Only background tasks notify — foreground runs return their result to the caller
// inline. The subscription is forward-only: notifications generated before
// Subscribe was first called are not replayed (use Get/List to inspect prior
// tasks). Multiple calls return the same channel (a single shared stream of
// notifications). The channel is closed by Close.
func (m *Manager) Subscribe() <-chan *Notification {
	m.subscribeOnce.Do(func() {
		m.notifyBuf = internal.NewUnboundedChan[*Notification]()
		m.notifyCh = make(chan *Notification)
		go m.relayNotifications()
	})
	return m.notifyCh
}

// relayNotifications pumps notifications from the unbounded buffer to the public
// channel, so sending under the Manager lock never blocks on a slow consumer.
func (m *Manager) relayNotifications() {
	defer close(m.notifyCh)
	for {
		n, ok := m.notifyBuf.Receive()
		if !ok {
			return
		}
		m.notifyCh <- n
	}
}

// WaitAllDone blocks until all registered tasks have reached a terminal state,
// or until the provided context is canceled.
func (m *Manager) WaitAllDone(ctx context.Context) error {
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			m.cond.Broadcast()
		case <-done:
		}
	}()

	m.mu.Lock()
	defer m.mu.Unlock()

	for m.hasRunningLocked() {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		m.cond.Wait()
	}
	return nil
}

// Close performs graceful shutdown.
// It waits for all running tasks to complete (up to the ctx deadline),
// then cancels any remaining running tasks.
// After Close returns, Run will return an error.
func (m *Manager) Close(ctx context.Context) error {
	_ = m.WaitAllDone(ctx)

	m.mu.Lock()
	defer m.mu.Unlock()

	m.closed = true

	for _, rec := range m.tasks {
		if !rec.done {
			m.cancelTask(rec)
		}
	}

	if m.notifyBuf != nil {
		m.notifyBuf.Close()
	}

	return nil
}

// createTask registers a new task in StatusRunning state.
// The cancel function is not set here — call storeCancelFunc after creation.
func (m *Manager) createTask(input *RunInput) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed {
		return "", fmt.Errorf("the background task manager has shut down and is no longer accepting new tasks. " +
			"Do not retry this; finish using any results you already have")
	}

	id := taskIDPrefix(input.Type) + "_" + base62(m.nextRawID())

	m.tasks[id] = &taskRecord{
		task: Task{
			ID:              id,
			Type:            input.Type,
			ToolUseID:       input.ToolUseID,
			Description:     input.Description,
			Status:          StatusRunning,
			RunInBackground: input.RunInBackground,
			CreatedAt:       time.Now(),
			OutputFile:      m.outputPath(id),
			Metadata:        cloneMetadata(input.Metadata),
		},
	}

	return id, nil
}

// cloneMetadata shallow-copies caller-supplied metadata so later mutations to the
// caller's map do not affect the recorded task. Returns nil for empty input.
func cloneMetadata(md map[string]any) map[string]any {
	if len(md) == 0 {
		return nil
	}
	clone := make(map[string]any, len(md))
	for k, v := range md {
		clone[k] = v
	}
	return clone
}

// storeCancelFunc saves the context cancel function for a running task,
// so that Cancel can stop it.
func (m *Manager) storeCancelFunc(id string, cancel context.CancelFunc) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.cancel = cancel
	}
}

// completeTask transitions a task to StatusCompleted with the given result.
// No-op if the task is already in a terminal state (idempotent).
func (m *Manager) completeTask(id string, result string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusCompleted
		rec.task.Result = result
	})
}

// outputPath returns the deterministic output-file path for a task, or "" when no
// output store is configured. The path is reserved at task creation so it can be
// surfaced before the file is actually written.
func (m *Manager) outputPath(id string) string {
	if m.outputStore == nil || m.outputDir == "" {
		return ""
	}
	return filepath.Join(m.outputDir, id+".output")
}

// persistOutput writes a completed task's result to its reserved output path via
// the configured OutputStore. Best-effort: with no store configured, or on a write
// error, it is a no-op and the task completes normally with its in-memory Result
// intact. Called outside m.mu (it may do I/O).
func (m *Manager) persistOutput(ctx context.Context, id, content string) {
	path := m.outputPath(id)
	if path == "" {
		return
	}
	_ = m.outputStore.Write(ctx, &filesystem.WriteRequest{FilePath: path, Content: content})
}

// failTask transitions a task to StatusFailed with the given error.
// No-op if the task is already in a terminal state (idempotent).
func (m *Manager) failTask(id string, err error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusFailed
		if err != nil {
			rec.task.Error = err.Error()
		}
	})
}

// timeoutTask transitions a task to StatusFailed with a timed-out error and
// cancels its context (the underlying work is stopped). It is invoked when a
// foreground run hits its deadline and the ShouldAutoBackground hook declined to
// background it. No-op if the task is already terminal (idempotent), so the
// timed-out reason wins the race against the work goroutine's own ctx-canceled error.
func (m *Manager) timeoutTask(id string, budgetMs int) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return
	}
	if rec.cancel != nil {
		rec.cancel()
	}
	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusFailed
		rec.task.Error = fmt.Sprintf("timed out after %dms", budgetMs)
	})
}

// canceledError is the message recorded on Task.Error when a task is stopped by
// Cancel or Close, so the canceled outcome carries a reason rather than an empty
// terminal state.
const canceledError = "task was canceled"

// cancelTask transitions a task to StatusCanceled and cancels its context.
// Must be called with m.mu held.
func (m *Manager) cancelTask(rec *taskRecord) {
	if rec.cancel != nil {
		rec.cancel()
	}

	m.finalize(rec.task.ID, func(rec *taskRecord) {
		rec.task.Status = StatusCanceled
		rec.task.Error = canceledError
	})
}

// cancelIfRunning cancels a task's work and marks it StatusCanceled if it is
// still running. Used when a foreground caller abandons its wait (its context is
// canceled before the task completes or auto-backgrounds). Idempotent: a no-op if
// the task already reached a terminal state.
func (m *Manager) cancelIfRunning(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return
	}
	m.cancelTask(rec)
}

// detach marks a still-running task as a background task, so its terminal
// transition will notify subscribers. It is called when Run hands the task back to
// the caller as StatusRunning (an explicit background launch, or an
// auto-background at the foreground deadline).
//
// Returns false if the task already reached a terminal state — i.e. the work
// finished concurrently with the deadline — in which case the caller should report
// the actual outcome instead of StatusRunning.
func (m *Manager) detach(id string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return false
	}
	rec.task.RunInBackground = true
	return true
}

// finalize applies a terminal state transition to a task.
// It sets done=true, records DoneAt, notifies subscribers (for background tasks),
// and broadcasts the condition.
// Returns false if the task was not found or already in a terminal state (idempotent).
// Must be called with m.mu held.
func (m *Manager) finalize(id string, apply func(rec *taskRecord)) bool {
	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return false
	}

	rec.done = true
	now := time.Now()
	rec.task.DoneAt = &now
	apply(rec)

	// Notify only for background tasks, and not for an explicit cancel: a
	// foreground run's result is returned to the caller inline, and a cancel was
	// requested by the caller (e.g. task_stop) who already knows — both would be
	// redundant notifications.
	if rec.task.RunInBackground && rec.task.Status != StatusCanceled {
		m.sendNotificationLocked(&Notification{Task: cloneTask(&rec.task)})
	}

	m.cond.Broadcast()
	return true
}

// sendNotificationLocked enqueues a notification to the subscriber, if any.
// Uses the unbounded buffer so it never blocks under m.mu. Must be called with m.mu held.
func (m *Manager) sendNotificationLocked(n *Notification) {
	if m.notifyBuf != nil {
		m.notifyBuf.TrySend(n)
	}
}

// cloneTask returns a copy of t safe to hand to callers. The Metadata map is
// shallow-copied so callers cannot mutate the registry's map entries, though
// mutable values stored inside Metadata remain shared.
func cloneTask(t *Task) *Task {
	clone := *t
	clone.Metadata = cloneMetadata(t.Metadata)
	return &clone
}

func (m *Manager) hasRunningLocked() bool {
	for _, rec := range m.tasks {
		if !rec.done {
			return true
		}
	}
	return false
}

// WorkFunc performs a single managed execution. It is supplied by the caller
// (e.g. a subagent or filesystem adapter); the Manager itself never knows what
// the work is.
//
// ctx carries the values of the Run call's context but is detached from its
// cancellation, so a backgrounded task outlives the turn that launched it. It is
// canceled when Cancel is invoked for this task, when a foreground deadline or an
// abandoned foreground wait stops it, or when the Manager is closed. Work should
// honor it.
//
// The returned result becomes Task.Result; a non-nil err becomes Task.Error and
// transitions the task to StatusFailed.
type WorkFunc func(ctx context.Context) (result string, err error)

// detachedCtx carries its parent's values but is never canceled by the parent.
// It mirrors context.WithoutCancel (Go 1.21+); this package targets Go 1.18.
// Background work runs under a detachedCtx (wrapped by a fresh cancelable context)
// so it survives cancellation of the per-turn context that launched it, while
// still seeing that context's values.
type detachedCtx struct{ parent context.Context }

func (detachedCtx) Deadline() (deadline time.Time, ok bool) { return time.Time{}, false }

func (detachedCtx) Done() <-chan struct{} { return nil }

func (detachedCtx) Err() error { return nil }

func (c detachedCtx) Value(key any) any { return c.parent.Value(key) }

// Run executes work as a managed task on m.
//
// The execution mode depends on input.RunInBackground and the effective foreground
// budget (input.ForegroundTimeoutMs if set, else the Manager's configured default):
//   - Foreground (RunInBackground=false, budget<=0): blocks until completion
//   - Background (RunInBackground=true): returns immediately with StatusRunning
//   - Deadline (budget>0): runs in foreground up to the budget, then — if still
//     running — consults the Manager's ShouldAutoBackground hook. If it permits,
//     the run is moved to the background (kept running) and Run returns
//     StatusRunning. Otherwise the run is canceled and reported as timed out
//     (StatusFailed).
//
// All runs are tracked in Manager state and visible via Get/List, and background
// runs notify subscribers on completion (see Subscribe).
func (m *Manager) Run(ctx context.Context, input *RunInput, work WorkFunc) (*RunResult, error) {
	id, err := m.createTask(input)
	if err != nil {
		return nil, err
	}

	// The work runs under a context detached from the caller's (per-turn)
	// cancellation, so a backgrounded task is not killed when the turn that
	// launched it ends or is preempted. The caller ctx's values are preserved
	// (framework/session state the work relies on); only its cancellation is
	// dropped. The work is stopped by Cancel(id), the foreground deadline, an
	// abandoned foreground wait (caller ctx canceled), or Close.
	runCtx, cancel := context.WithCancel(detachedCtx{parent: ctx})
	m.storeCancelFunc(id, cancel)

	// run executes the work and finalizes the task. The terminal outcome lives on
	// the task record (set by completeTask/failTask), which Run reads back via
	// toRunResultByID — so run signals completion rather than returning a value.
	run := func() {
		defer cancel()
		r, runErr := work(runCtx)
		if runErr != nil {
			m.failTask(id, runErr)
		} else {
			// Persist the result before finalizing (outside the lock), so the
			// output file is in place by the time subscribers see the completion.
			m.persistOutput(runCtx, id, r)
			m.completeTask(id, r)
		}
	}

	// Explicit background: run in goroutine, return immediately. createTask already
	// marked the task RunInBackground, so its terminal transition will notify.
	if input.RunInBackground {
		go run()
		return m.runningResult(id), nil
	}

	// Foreground: run in a goroutine and wait. The wait honors caller cancellation
	// (the detached work ctx does not, so it is canceled explicitly here) and, when a
	// budget is set, the foreground deadline.
	done := make(chan struct{}, 1)
	go func() { run(); done <- struct{}{} }()

	budgetMs := m.foregroundTimeoutMs
	if input.ForegroundTimeoutMs != nil {
		budgetMs = *input.ForegroundTimeoutMs
	}

	if budgetMs > 0 {
		// Foreground with a deadline: wait up to the effective budget (per-run
		// override takes precedence over the Manager default). On the deadline,
		// either move to the background (if the hook permits) or cancel as timed out.
		timer := time.NewTimer(time.Duration(budgetMs) * time.Millisecond)
		defer timer.Stop()
		select {
		case <-done:
			// run() has already finalized the task before signaling, so the recorded
			// state is authoritative — including a StatusCanceled set by a concurrent
			// Cancel, which must win over the work's own ctx-canceled error.
			return m.toRunResultByID(id), nil
		case <-ctx.Done():
			// Caller abandoned the foreground wait before the deadline (e.g. the
			// turn was canceled) and before any auto-background: stop the work.
			m.cancelIfRunning(id)
			return m.toRunResultByID(id), nil
		case <-timer.C:
			task, ok := m.Get(id)
			if !ok || task.DoneAt != nil {
				// Work finished right at the deadline — report its actual outcome.
				return m.toRunResultByID(id), nil
			}
			if m.allowAutoBackground(ctx, task) && m.detach(id) {
				return m.runningResult(id), nil
			}
			// Hook declined (or work finished during the hook): stop if still running.
			m.timeoutTask(id, budgetMs)
			return m.toRunResultByID(id), nil
		}
	}

	// Foreground without a deadline: block until completion or caller cancellation.
	select {
	case <-done:
		return m.toRunResultByID(id), nil
	case <-ctx.Done():
		m.cancelIfRunning(id)
		return m.toRunResultByID(id), nil
	}
}

// StreamWorkFunc performs a single managed streaming execution. It is the
// streaming counterpart of WorkFunc: instead of returning the whole result at
// once, it returns a stream of output chunks. The Manager forwards those chunks
// to the RunStream caller in real time and, in parallel, accumulates them into
// the task's final Result (and OutputFile). Chunk semantics (formatting, exit
// codes) are entirely the caller's concern; the Manager only concatenates.
//
// ctx behaves exactly as for WorkFunc (see WorkFunc): detached from the caller's
// cancellation, stopped by Cancel/deadline/Close. Work should honor it and close
// the returned reader when ctx is done.
type StreamWorkFunc func(ctx context.Context) (*schema.StreamReader[string], error)

// RunStream executes streaming work as a managed task, returning a stream of
// output chunks to consume in real time.
//
// It mirrors Run's lifecycle (tracking, foreground budget, auto-background,
// notifications) but preserves streaming for the foreground phase:
//   - Foreground completion: every chunk is forwarded live, then the stream closes.
//   - Auto-background at the deadline: chunks forwarded so far are kept; the
//     Manager appends a single notice chunk (task id + output file) and closes the
//     caller's stream, while the work keeps running in the background — its
//     remaining output is drained into the task's Result/OutputFile and a terminal
//     notification fires on completion (see Subscribe).
//   - Explicit background (input.RunInBackground): the work runs detached from the
//     start, so no execution chunks reach the caller; the stream carries only the
//     background notice and then closes.
//
// The returned reader is always non-nil on a nil error. The Manager is the sole
// writer of that stream, so there is never a write race with the work.
func (m *Manager) RunStream(ctx context.Context, input *RunInput, work StreamWorkFunc) (*schema.StreamReader[string], error) {
	id, err := m.createTask(input)
	if err != nil {
		return nil, err
	}

	runCtx, cancel := context.WithCancel(detachedCtx{parent: ctx})
	m.storeCancelFunc(id, cancel)

	sr, sw := schema.Pipe[string](streamBufferCap)

	budgetMs := m.foregroundTimeoutMs
	if input.ForegroundTimeoutMs != nil {
		budgetMs = *input.ForegroundTimeoutMs
	}
	// An explicit background launch has no foreground phase to stream, so its
	// budget is irrelevant: forward nothing, just emit the notice.
	if input.RunInBackground {
		budgetMs = 0
	}

	go m.forwardStream(&streamRun{
		callerCtx: ctx,
		runCtx:    runCtx,
		cancel:    cancel,
		id:        id,
		input:     input,
		work:      work,
		sw:        sw,
		budgetMs:  budgetMs,
	})
	return sr, nil
}

// streamRun bundles the per-run state for forwardStream (kept as one value to stay
// within the argument limit and to make the goroutine launch self-documenting).
type streamRun struct {
	callerCtx context.Context
	runCtx    context.Context
	cancel    context.CancelFunc
	id        string
	input     *RunInput
	work      StreamWorkFunc
	sw        *schema.StreamWriter[string]
	budgetMs  int
}

// forwardStream owns the caller-facing stream writer sw: it is the only goroutine
// that writes to it, so injecting the background notice never races the work.
func (m *Manager) forwardStream(r *streamRun) {
	defer r.cancel()

	ws, err := r.work(r.runCtx)
	if err != nil {
		m.failTask(r.id, err)
		r.sw.Send("", err)
		r.sw.Close()
		return
	}
	defer ws.Close()

	chunks := pumpStream(r.runCtx, ws)

	var buf strings.Builder

	var timerC <-chan time.Time
	if r.budgetMs > 0 {
		timer := time.NewTimer(time.Duration(r.budgetMs) * time.Millisecond)
		defer timer.Stop()
		timerC = timer.C
	}

	// Explicit background: do not forward execution chunks. Emit the notice
	// immediately, close the caller stream, and drain the rest into the result.
	if r.input.RunInBackground {
		r.sw.Send(m.backgroundNotice(r.id), nil)
		r.sw.Close()
		m.drainStream(r.runCtx, r.id, chunks, &buf)
		return
	}

	for {
		select {
		case c := <-chunks:
			if c.err == io.EOF {
				m.persistOutput(r.runCtx, r.id, buf.String())
				m.completeTask(r.id, buf.String())
				r.sw.Close()
				return
			}
			if c.err != nil {
				m.failTask(r.id, c.err)
				r.sw.Send("", c.err)
				r.sw.Close()
				return
			}
			buf.WriteString(c.text)
			if r.sw.Send(c.text, nil) {
				// Caller closed the stream early (abandoned the read): stop the work.
				m.cancelIfRunning(r.id)
				return
			}
		case <-r.callerCtx.Done():
			// Caller abandoned the foreground wait before the deadline: stop work.
			m.cancelIfRunning(r.id)
			r.sw.Close()
			return
		case <-timerC:
			task, ok := m.Get(r.id)
			if !ok || task.DoneAt != nil {
				continue // finished right at the deadline; let the chunks case end it
			}
			if m.allowAutoBackground(r.callerCtx, task) && m.detach(r.id) {
				// Moved to the background: cap the caller's stream with a notice and
				// keep draining the rest into the task result.
				r.sw.Send(m.backgroundNotice(r.id), nil)
				r.sw.Close()
				m.drainStream(r.runCtx, r.id, chunks, &buf)
				return
			}
			m.timeoutTask(r.id, r.budgetMs)
			r.sw.Close()
			return
		}
	}
}

// streamChunk is one item pumped off a StreamWorkFunc's reader: either a piece of
// output text or a terminal error (io.EOF on normal completion).
type streamChunk struct {
	text string
	err  error
}

// pumpStream turns a stream reader's blocking Recv loop into a channel, so the
// forward loop can wait on output alongside the deadline and caller cancellation.
// It stops when ctx is done (the run was canceled, timed out, or closed).
func pumpStream(ctx context.Context, ws *schema.StreamReader[string]) <-chan streamChunk {
	chunks := make(chan streamChunk)
	go func() {
		for {
			text, err := ws.Recv()
			c := streamChunk{text: text, err: err}
			select {
			case chunks <- c:
			case <-ctx.Done():
				return
			}
			if err != nil {
				return
			}
		}
	}()
	return chunks
}

// drainStream consumes a backgrounded run's remaining chunks into buf and
// finalizes the task on completion. Called after the caller's stream has been
// closed, so it never writes to sw.
func (m *Manager) drainStream(runCtx context.Context, id string, chunks <-chan streamChunk, buf *strings.Builder) {
	for {
		select {
		case c := <-chunks:
			if c.err == io.EOF {
				m.persistOutput(runCtx, id, buf.String())
				m.completeTask(id, buf.String())
				return
			}
			if c.err != nil {
				m.failTask(id, c.err)
				return
			}
			buf.WriteString(c.text)
		case <-runCtx.Done():
			// The run was canceled/closed while backgrounded; finalize already
			// happened via cancelTask, so just stop draining.
			return
		}
	}
}

// backgroundNotice builds the generic chunk appended when a task moves to the
// background. It uses only Manager-level facts (type, id, output file), so it
// stays domain-agnostic.
func (m *Manager) backgroundNotice(id string) string {
	task, ok := m.Get(id)
	kind := ""
	if ok && task.Type != "" {
		kind = " (" + task.Type + ")"
	}
	msg := fmt.Sprintf("\n[task %s%s moved to the background; you will be notified when it completes", id, kind)
	if ok && task.OutputFile != "" {
		msg += fmt.Sprintf(". Output: %s", task.OutputFile)
	}
	return msg + ". Use task_output to retrieve the result.]"
}

// streamBufferCap is the buffer size of the caller-facing stream pipe.
const streamBufferCap = 16

// runningResult builds the RunResult handed back when a task is left running in
// the background. The output-file path is deterministic and reserved at launch
// (see Task.OutputFile), so the caller can surface it to the agent immediately.
func (m *Manager) runningResult(id string) *RunResult {
	return &RunResult{TaskID: id, Status: StatusRunning, OutputFile: m.outputPath(id)}
}

// toRunResultByID builds a RunResult from a task's current (terminal) state. The
// task record is the single source of truth, so a concurrent cancel or timeout is
// reflected faithfully.
func (m *Manager) toRunResultByID(id string) *RunResult {
	task, ok := m.Get(id)
	if !ok {
		return &RunResult{TaskID: id, Status: StatusFailed}
	}
	return &RunResult{TaskID: id, Status: task.Status, Result: task.Result, Error: task.Error, OutputFile: task.OutputFile}
}
