/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package backgroundtask provides a shared lifecycle registry for long-running
// executions (sub-agents, shell commands, ...) that may outlive the tool call
// that launched them.
//
// The central type is Manager: a non-generic, in-memory registry that tracks
// foreground/background/auto-background runs and exposes them via Get/List/
// Cancel/Wait/Close. Manager is deliberately non-generic so a single instance
// can be shared across heterogeneous domains (e.g. agent runs and shell runs)
// under one unified task-ID space.
//
// What a run actually does is supplied per-call as a WorkFunc passed to Run, which
// keeps the engine agnostic to what it runs (agents, shell, ...); adapters that
// produce WorkFunc values live in the consuming packages (subagent, filesystem).
// A task may carry an output-file path (RunInput.OutputFile) that the launcher
// writes to; the Manager only records and surfaces the path, never the file.
//
// Manager tracks lifecycle only. Streaming a specific run's events in real time
// is intentionally out of scope here: the launcher (a domain adapter) already
// knows the concrete event type, so live streaming, if needed, belongs at that
// typed layer rather than behind a type-erased registry-wide channel.
package backgroundtask

import (
	"context"
	"fmt"
	"io"
	"runtime/debug"
	"strings"
	"sync"
	"time"

	"github.com/cloudwego/eino/internal"
	"github.com/cloudwego/eino/internal/safe"
	"github.com/cloudwego/eino/schema"
)

// Status represents the lifecycle status of a task.
type Status string

const (
	// StatusRunning indicates the task is currently executing.
	StatusRunning Status = "running"
	// StatusCompleted indicates the task finished successfully.
	StatusCompleted Status = "completed"
	// StatusFailed indicates the task terminated with an error.
	StatusFailed Status = "failed"
	// StatusCanceled indicates the task was stopped by an external request
	// (Cancel / Close) via context cancellation.
	StatusCanceled Status = "canceled"
)

// Task represents a single managed execution record.
type Task struct {
	// ID is the unique identifier for this task, generated by Manager.
	ID string
	// Type is a caller-supplied tag (e.g. "bash", "subagent") identifying what kind
	// of work this task runs. The Manager does not interpret it; it lets the
	// ShouldAutoBackground hook and observers distinguish domains without parsing
	// Description. Empty if the launcher did not set it.
	Type string
	// ToolUseID is the id of the tool call that launched this task, when known.
	// It lets a host correlate a task event back to the originating tool call.
	// Empty if the launcher did not set it.
	ToolUseID string
	// Description is a human-readable summary of what the task does.
	Description string
	// Status is the current lifecycle status.
	Status Status
	// Result contains the task output, set when Status is StatusCompleted.
	Result string
	// OutputFile is the path the task's output is written to, when the launcher
	// supplied one via RunInput.OutputFile. Empty otherwise. The Manager only
	// records and surfaces this path (in notices and Get/List); it never writes
	// the file — the launcher's work owns writing, so it may contain interim
	// output while the task is still running. The file outlives the in-memory
	// record, so it remains readable after the Manager is rebuilt.
	OutputFile string
	// OutputFileErr is set by the launcher (via MarkOutputFileUnreliable) when a
	// write to OutputFile fails, so the file is known to be incomplete. It is
	// empty while the file is trustworthy. When non-empty, neither OutputFile nor
	// Result can be treated as the authoritative complete output: the file has a
	// gap, and Result is only whatever the worker returned (which may be empty
	// while the task is still running, and — depending on the worker — may be a
	// partial projection of the file rather than its full content). Consumers
	// should report the file's failed state honestly rather than present either
	// side as complete. The Manager does not interpret the value beyond emptiness;
	// it carries the first failure's message for diagnostics.
	OutputFileErr string
	// Error contains the error message, set when Status is StatusFailed.
	Error string
	// RunInBackground indicates whether this task is running (or ran) in the
	// background — either launched with RunInBackground, or moved to the background
	// after reaching its foreground timeout. It distinguishes background tasks
	// from foreground ones when inspecting task state.
	RunInBackground bool
	// CreatedAt is the time the task was registered.
	CreatedAt time.Time
	// DoneAt is the time the task reached a terminal state. Nil if still running.
	DoneAt *time.Time
	// Metadata holds arbitrary extensible fields for future use.
	Metadata map[string]any
}

// TaskEventType describes the lifecycle transition that caused a task event.
type TaskEventType string

const (
	// TaskEventCreated indicates a task was registered in StatusRunning.
	TaskEventCreated TaskEventType = "created"
	// TaskEventBackgrounded indicates a foreground task moved to the background.
	TaskEventBackgrounded TaskEventType = "backgrounded"
	// TaskEventCompleted indicates a task finished successfully.
	TaskEventCompleted TaskEventType = "completed"
	// TaskEventFailed indicates a task finished with an error.
	TaskEventFailed TaskEventType = "failed"
	// TaskEventCanceled indicates a task was canceled by Cancel / Close.
	TaskEventCanceled TaskEventType = "canceled"
)

// TaskEvent is a lifecycle event published by Manager.Subscribe.
type TaskEvent struct {
	// Type is the transition that caused this event.
	Type TaskEventType
	// Task is the task snapshot immediately after the transition.
	Task *Task
}

// RunInput is the execution-agnostic input for Run.
// Domain-specific parameters (which agent, which command, the prompt) are
// captured by the WorkFunc closure, not here.
type RunInput struct {
	// Description is a short human-readable title for the task, stored in Task.Description.
	Description string
	// Type is an optional tag for the task (e.g. "bash", "subagent"), stored in
	// Task.Type. See Task.Type.
	Type string
	// ToolUseID is the optional id of the tool call launching this task, stored in
	// Task.ToolUseID. See Task.ToolUseID.
	ToolUseID string
	// RunInBackground starts the task in the background. Run returns an initial
	// StatusRunning snapshot without waiting for the work. RunStream returns its
	// caller-facing stream without waiting; consuming that stream normally yields
	// the background notice, optionally preceded by a bounded startup preview. If
	// the work reaches a terminal state during the preview, the stream instead
	// ends after forwarding all work chunks, without a background notice.
	RunInBackground bool
	// BackgroundStartupPreviewMs keeps an explicit-background RunStream caller's
	// stream open for up to this many milliseconds and forwards work chunks emitted
	// during that startup window. When the window expires, RunStream appends the
	// normal background notice, closes the caller stream, and drains the remaining
	// work output in the background. This lets launch-time information such as an
	// OAuth URL remain visible without changing the task's background lifecycle. If
	// the work finishes during the window, all chunks are forwarded and the caller
	// stream closes without a background notice; the task is already terminal then.
	// A value <= 0 disables the preview. Ignored by Run and by foreground RunStream
	// executions (including their later auto-background transition).
	//
	// The window is measured from when the StreamWorkFunc returns its reader (see
	// StreamWorkFunc), so it bounds the preview of streamed output, not the work's
	// initialization; streaming work must return its reader promptly for the window
	// to be meaningful.
	BackgroundStartupPreviewMs int
	// Metadata is optional caller-supplied data attached to the task's Task.Metadata.
	// It is for observers (Get/List, the task_output tool, the host) to correlate or
	// label background tasks — e.g. an originating tool-call ID, session, or trace.
	// The Manager does not interpret it. It is shallow-copied into the task on creation.
	Metadata map[string]any
	// OutputFile is the optional path the launcher will write this task's output
	// to. When non-empty it is recorded on Task.OutputFile and surfaced in the
	// background notice; the Manager itself never writes the file. The launcher
	// (a domain adapter) owns writing, so the file may carry interim output while
	// the task runs. Empty means the task has no output file.
	OutputFile string
	// ForegroundTimeoutMs optionally overrides the Manager's foreground timeout for
	// this run only. When nil, the Manager's configured default applies. When non-nil,
	// it bounds how long the run may occupy the foreground before its deadline fires
	// (see Config.ShouldAutoBackground for what happens at the deadline). A value <= 0
	// removes the deadline for this run (blocks until completion). Ignored when
	// RunInBackground is true.
	//
	// For Run the deadline is measured from when the work starts; for RunStream it is
	// measured from when the work returns its stream reader (see StreamWorkFunc), so
	// streaming work must return its reader promptly for the two to coincide.
	ForegroundTimeoutMs *int
}

// defaultForegroundTimeoutMs is the default foreground timeout (120 seconds).
const defaultForegroundTimeoutMs = 120_000

// IDGenerator returns the complete ID for a new task.
//
// The generator sees the run input before the task is registered and may return a
// business-side identifier. Manager does not add the task-type prefix when IDGen
// is configured; callers that want one should include it in the returned ID.
type IDGenerator func(ctx context.Context, input *RunInput) (string, error)

// Config configures a Manager.
type Config struct {
	// ForegroundTimeoutMs sets the foreground timeout: the time a foreground run is
	// allowed to occupy the foreground before its deadline fires.
	// When > 0, a foreground run that hasn't completed within this many
	// milliseconds reaches its deadline (see ShouldAutoBackground for what happens then).
	// When 0, there is no deadline (foreground runs block until completion).
	//
	// Default: 120000ms (120 seconds).
	ForegroundTimeoutMs *int

	// ShouldAutoBackground decides, at a foreground run's deadline, whether it may be
	// moved to the background (kept running) instead of being canceled. Applications
	// can use it to permit long-lived workloads such as servers and watchers while
	// timing out commands whose results are no longer useful. The hook receives the
	// task, so a host can branch on Task.Type and recover domain parameters from
	// Task.Metadata (e.g. the shell command via filesystem.CommandFromTask).
	//
	// Deciding whether a workload is genuinely long-lived is inherently host- and
	// command-specific, so this package ships no built-in policy: the framework
	// cannot reliably infer "never exits" from a command string, and a wrong guess
	// either kills a useful run or keeps a doomed one. Hosts encode their own rules.
	//
	// It is consulted ONLY for the auto path — a foreground run that hits its
	// deadline. An explicit RunInBackground run always backgrounds immediately,
	// regardless of this hook.
	//
	// When nil (the default), it is treated as always returning false: a run that
	// hits its deadline is canceled and reported as timed out, never auto-backgrounded.
	ShouldAutoBackground func(ctx context.Context, task *Task) bool

	// IDGen, when set, decides the full ID of every task created by this Manager.
	// If nil, Manager uses its default task-type-prefixed base62 ID.
	//
	// IDGen may be called concurrently by concurrent Run / RunStream calls. It
	// must return a non-empty ID. The returned ID must be unique among this
	// Manager's registered tasks; a duplicate fails task creation.
	IDGen IDGenerator

	// BackgroundNotice customizes the chunk emitted on a RunStream caller's stream
	// when a task starts in the background or is auto-moved there. The Manager owns
	// only lifecycle facts (id, type, output file); how a host tells the model to
	// retrieve the result is host-specific — one host exposes a task_output tool,
	// another points at the output file — so that wording does not belong in this
	// type-erased layer.
	//
	// When nil, defaultBackgroundNotice is used: it announces the background launch
	// and, when an output file is reserved, directs the reader to Read that path for
	// interim output.
	//
	// The ctx passed to the hook is the run's context (detached from the caller's
	// cancellation, carrying its values); use it only for value lookup, not to gate
	// the notice on cancellation.
	BackgroundNotice func(ctx context.Context, info NoticeInfo) string
}

// NoticeInfo carries the lifecycle facts a BackgroundNotice hook may use to build
// the chunk shown when a run goes to the background.
type NoticeInfo struct {
	// Task is a snapshot of the task at the moment the notice is emitted, carrying
	// ID, Type, and OutputFile. Nil only if the task vanished mid-emit (not expected).
	Task *Task
	// AutoBackgrounded is false when the run was launched directly in the background
	// (RunInBackground), and true when a foreground run was auto-moved to the
	// background at its deadline because the ShouldAutoBackground hook permitted it
	// (a deadline the hook declines becomes a timeout failure, which never reaches
	// this notice). The true case is the same transition reported to subscribers as
	// TaskEventBackgrounded.
	AutoBackgrounded bool
}

// Manager is a non-generic, in-memory registry that owns the lifecycle of
// managed executions: creation, foreground/background/auto-background
// switching, cancellation and terminal-state tracking.
//
// It is intentionally execution-agnostic: it does not know whether a task is an
// agent or a shell command. Callers launch work via the free function Run,
// passing a WorkFunc that performs the actual execution. A single Manager can
// therefore be shared across multiple domains under one task-ID space.
type Manager struct {
	mu                   sync.Mutex
	cond                 *sync.Cond
	tasks                map[string]*taskRecord
	seq                  int64
	lastMs               int64
	closed               bool
	foregroundTimeoutMs  int
	shouldAutoBackground func(ctx context.Context, task *Task) bool
	idGen                IDGenerator
	backgroundNoticeFn   func(ctx context.Context, info NoticeInfo) string

	subscribeOnce sync.Once
	eventCh       chan *TaskEvent
	eventBuf      *internal.UnboundedChan[*TaskEvent]
}

type taskRecord struct {
	task   Task
	cancel context.CancelFunc // cancels the run's context
	// doneCh is closed exactly once, by finalize, when the task reaches a terminal
	// state. Wait selects on it so waiting for one task neither holds m.mu nor is
	// woken by unrelated tasks finishing.
	doneCh chan struct{}
	// backgrounded is closed exactly once (guarded by bgClosed) when the task moves
	// to background execution: before the work starts for an explicit
	// RunInBackground launch, or at the auto-background transition (detach). It stays
	// open for a run that completes in the foreground. Handed to the work via
	// TaskInfo.Backgrounded so foreground-only side effects can stop when it fires.
	backgrounded chan struct{}
	bgClosed     bool
}

// New creates a new Manager.
// By default, the foreground timeout is 120 seconds; set Config.ForegroundTimeoutMs
// to 0 to remove the deadline (foreground runs block until completion). What
// happens when the timeout is reached is governed by Config.ShouldAutoBackground
// (default: cancel the run and report it timed out).
func New(_ context.Context, conf *Config) *Manager {
	m := &Manager{
		tasks:               make(map[string]*taskRecord),
		foregroundTimeoutMs: defaultForegroundTimeoutMs,
	}
	m.cond = sync.NewCond(&m.mu)
	if conf != nil && conf.ForegroundTimeoutMs != nil {
		m.foregroundTimeoutMs = *conf.ForegroundTimeoutMs
	}
	if conf != nil {
		m.shouldAutoBackground = conf.ShouldAutoBackground
		m.idGen = conf.IDGen
		m.backgroundNoticeFn = conf.BackgroundNotice
	}
	return m
}

// Subscribe returns a channel that receives TaskEvent values whenever the Manager
// changes a task's lifecycle state.
//
// The stream is forward-only: events generated before the first Subscribe call
// are not replayed (use Get/List to inspect current state). Multiple calls return
// the same shared stream, and Close closes it after buffered events are drained.
// The returned Task values are snapshots; mutating them does not mutate the
// Manager's registry.
func (m *Manager) Subscribe() <-chan *TaskEvent {
	m.subscribeOnce.Do(func() {
		buf := internal.NewUnboundedChan[*TaskEvent]()
		ch := make(chan *TaskEvent)

		m.mu.Lock()
		m.eventBuf = buf
		m.eventCh = ch
		closed := m.closed
		m.mu.Unlock()

		go m.relayEvents(buf, ch)
		if closed {
			buf.Close()
		}
	})
	return m.eventCh
}

// relayEvents pumps events from the unbounded buffer to the public channel,
// so publishing under the Manager lock never blocks on a slow subscriber.
func (m *Manager) relayEvents(buf *internal.UnboundedChan[*TaskEvent], ch chan<- *TaskEvent) {
	defer close(ch)
	for {
		event, ok := buf.Receive()
		if !ok {
			return
		}
		ch <- event
	}
}

// allowAutoBackground reports whether a run that has hit its foreground deadline
// may be moved to the background. With no configured hook, the answer is false.
func (m *Manager) allowAutoBackground(ctx context.Context, task *Task) bool {
	if m.shouldAutoBackground == nil {
		return false
	}
	return m.shouldAutoBackground(ctx, task)
}

// Get returns the current state of a task by ID.
// Returns (nil, false) if the task does not exist.
func (m *Manager) Get(id string) (*Task, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return nil, false
	}
	return cloneTask(&rec.task), true
}

// Wait blocks until the task with the given id reaches a terminal state, or until
// ctx is canceled, and returns the task's current snapshot together with whether it
// actually reached a terminal state. Callers bound the wait with ctx (e.g.
// context.WithTimeout).
//
// Return values:
//   - (nil, false): no task with this id exists.
//   - (task, true): the task reached a terminal state (task.Status is terminal).
//   - (task, false): ctx was canceled/timed out first; task is the latest
//     (still-running) snapshot.
//
// The wait is per-task: it selects on the task's own done channel rather than the
// shared condition, so it neither holds m.mu while waiting nor is woken when other
// tasks finish.
func (m *Manager) Wait(ctx context.Context, id string) (*Task, bool) {
	m.mu.Lock()
	rec, ok := m.tasks[id]
	if !ok {
		m.mu.Unlock()
		return nil, false
	}
	doneCh := rec.doneCh
	m.mu.Unlock()

	select {
	case <-doneCh:
	case <-ctx.Done():
		return m.taskSnapshot(id), false
	}
	return m.taskSnapshot(id), true
}

// List returns a snapshot of all tasks (both running and completed).
func (m *Manager) List() []*Task {
	m.mu.Lock()
	defer m.mu.Unlock()

	tasks := make([]*Task, 0, len(m.tasks))
	for _, rec := range m.tasks {
		tasks = append(tasks, cloneTask(&rec.task))
	}
	return tasks
}

// Cancel stops a running task. The run's context is canceled and the task
// transitions to StatusCanceled.
// Returns an error if the task does not exist or is not running.
func (m *Manager) Cancel(id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return fmt.Errorf("no background task has id %q, so there is nothing to stop. "+
			"If you are unsure of the id, there is nothing left to cancel", id)
	}
	if taskDone(rec.doneCh) {
		return fmt.Errorf("background task %q has already finished (status: %s) and cannot be stopped. "+
			"Use the task_output tool with this id to read its result instead", id, rec.task.Status)
	}

	m.cancelTask(rec)
	return nil
}

// waitIdle blocks until no registered task is still running, or until the
// provided context is canceled. It backs graceful Close; single-task waits use
// Wait.
func (m *Manager) waitIdle(ctx context.Context) error {
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			m.cond.Broadcast()
		case <-done:
		}
	}()

	m.mu.Lock()
	defer m.mu.Unlock()

	for m.hasRunningLocked() {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		m.cond.Wait()
	}
	return nil
}

// Close performs graceful shutdown.
// It waits for all running tasks to complete (up to the ctx deadline),
// then cancels any remaining running tasks.
// After Close returns, Run will return an error.
func (m *Manager) Close(ctx context.Context) error {
	_ = m.waitIdle(ctx)

	m.mu.Lock()
	defer m.mu.Unlock()

	m.closed = true

	for _, rec := range m.tasks {
		if !taskDone(rec.doneCh) {
			m.cancelTask(rec)
		}
	}
	if m.eventBuf != nil {
		m.eventBuf.Close()
	}

	return nil
}

// createTask registers a new task in StatusRunning state.
// The cancel function is not set here — call storeCancelFunc after creation.
func (m *Manager) createTask(ctx context.Context, input *RunInput) (string, error) {
	if input == nil {
		return "", fmt.Errorf("backgroundtask: RunInput is required")
	}

	if m.idGen != nil {
		id, err := m.idGen(ctx, input)
		if err != nil {
			return "", fmt.Errorf("backgroundtask: task id generator: %w", err)
		}
		return m.registerTask(input, id)
	}

	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed {
		return "", m.closedError()
	}

	id := taskIDPrefix(input.Type) + "_" + base62(m.nextRawID())
	return m.registerTaskLocked(input, id)
}

func (m *Manager) registerTask(input *RunInput, id string) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed {
		return "", m.closedError()
	}
	return m.registerTaskLocked(input, id)
}

func (m *Manager) registerTaskLocked(input *RunInput, id string) (string, error) {
	if id == "" {
		return "", fmt.Errorf("backgroundtask: task id generator returned empty id")
	}
	if _, ok := m.tasks[id]; ok {
		return "", fmt.Errorf("backgroundtask: task id %q already exists", id)
	}

	m.tasks[id] = &taskRecord{
		task: Task{
			ID:              id,
			Type:            input.Type,
			ToolUseID:       input.ToolUseID,
			Description:     input.Description,
			Status:          StatusRunning,
			RunInBackground: input.RunInBackground,
			CreatedAt:       time.Now(),
			OutputFile:      input.OutputFile,
			Metadata:        cloneMetadata(input.Metadata),
		},
		doneCh:       make(chan struct{}),
		backgrounded: make(chan struct{}),
	}
	m.sendEventLocked(m.tasks[id], TaskEventCreated)

	return id, nil
}

// markBackgroundedLocked closes a task's backgrounded signal, idempotently. Must be
// called with m.mu held.
func (m *Manager) markBackgroundedLocked(rec *taskRecord) {
	if !rec.bgClosed {
		rec.bgClosed = true
		close(rec.backgrounded)
	}
}

// backgroundedCh returns the task's backgrounded signal channel. Returns a nil
// channel if the task is absent (should not happen for a just-created task); a nil
// channel never fires, which is the correct "stayed foreground" reading.
func (m *Manager) backgroundedCh(id string) <-chan struct{} {
	m.mu.Lock()
	defer m.mu.Unlock()
	if rec, ok := m.tasks[id]; ok {
		return rec.backgrounded
	}
	return nil
}

// markBackgrounded closes a task's backgrounded signal, idempotently. Used for an
// explicit RunInBackground launch, where the run is background from the start.
func (m *Manager) markBackgrounded(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if rec, ok := m.tasks[id]; ok {
		m.markBackgroundedLocked(rec)
	}
}

func (m *Manager) closedError() error {
	return fmt.Errorf("the background task manager has shut down and is no longer accepting new tasks. " +
		"Do not retry this; finish using any results you already have")
}

// cloneMetadata shallow-copies caller-supplied metadata so later mutations to the
// caller's map do not affect the recorded task. Returns nil for empty input.
func cloneMetadata(md map[string]any) map[string]any {
	if len(md) == 0 {
		return nil
	}
	clone := make(map[string]any, len(md))
	for k, v := range md {
		clone[k] = v
	}
	return clone
}

// storeCancelFunc saves the context cancel function for a running task,
// so that Cancel can stop it.
func (m *Manager) storeCancelFunc(id string, cancel context.CancelFunc) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.cancel = cancel
	}
}

// MarkOutputFileUnreliable records that a write to the task's output file failed,
// so the file is known to be incomplete. The launcher that owns writing calls it
// (with the task id it receives via WorkFunc's TaskInfo) when an append to the
// file errors.
//
// It sets Task.OutputFileErr on the task with the given id, so consumers stop
// trusting the partial file. The first failure wins: a later call does not
// overwrite an existing message, since once the file has a gap it is unreliable
// regardless of what later writes do. An empty id, an unknown id, or an
// already-marked task is a no-op, so callers may invoke it unconditionally on
// write error.
func (m *Manager) MarkOutputFileUnreliable(taskID, errMsg string) {
	if taskID == "" {
		return
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[taskID]; ok && rec.task.OutputFileErr == "" {
		rec.task.OutputFileErr = errMsg
	}
}

// completeTask transitions a task to StatusCompleted with the given result.
// No-op if the task is already in a terminal state (idempotent).
func (m *Manager) completeTask(id string, result string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusCompleted
		rec.task.Result = result
	})
}

// failTask transitions a task to StatusFailed with the given error.
// No-op if the task is already in a terminal state (idempotent).
func (m *Manager) failTask(id string, err error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusFailed
		if err != nil {
			rec.task.Error = err.Error()
		}
	})
}

// timeoutTask transitions a task to StatusFailed with a timed-out error and
// cancels its context (the underlying work is stopped). It is invoked when a
// foreground run hits its deadline and the ShouldAutoBackground hook declined to
// background it. No-op if the task is already terminal (idempotent), so the
// timed-out reason wins the race against the work goroutine's own ctx-canceled error.
func (m *Manager) timeoutTask(id string, foregroundTimeoutMs int) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || taskDone(rec.doneCh) {
		return
	}
	if rec.cancel != nil {
		rec.cancel()
	}
	m.finalize(id, func(rec *taskRecord) {
		rec.task.Status = StatusFailed
		rec.task.Error = fmt.Sprintf("timed out after %dms", foregroundTimeoutMs)
	})
}

// canceledError is the message recorded on Task.Error when a task is stopped by
// Cancel or Close, so the canceled outcome carries a reason rather than an empty
// terminal state.
const canceledError = "task was canceled"

// cancelTask transitions a task to StatusCanceled and cancels its context.
// Must be called with m.mu held.
func (m *Manager) cancelTask(rec *taskRecord) {
	if rec.cancel != nil {
		rec.cancel()
	}

	m.finalize(rec.task.ID, func(rec *taskRecord) {
		rec.task.Status = StatusCanceled
		rec.task.Error = canceledError
	})
}

// cancelIfRunning cancels a task's work and marks it StatusCanceled if it is
// still running. Used when a foreground caller abandons its wait (its context is
// canceled before the task completes or auto-backgrounds). Idempotent: a no-op if
// the task already reached a terminal state.
func (m *Manager) cancelIfRunning(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || taskDone(rec.doneCh) {
		return
	}
	m.cancelTask(rec)
}

// detach marks a still-running task as a background task and publishes an event.
// It is called when Run hands the task back to the caller as StatusRunning (an
// explicit background launch, or an auto-background at the foreground deadline).
//
// Returns false if the task already reached a terminal state — i.e. the work
// finished concurrently with the deadline — in which case the caller should report
// the actual outcome instead of StatusRunning.
func (m *Manager) detach(id string) bool {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok || taskDone(rec.doneCh) {
		return false
	}
	rec.task.RunInBackground = true
	m.markBackgroundedLocked(rec)
	m.sendEventLocked(rec, TaskEventBackgrounded)
	return true
}

// finalize applies a terminal state transition to a task.
// It sets done=true, records DoneAt, publishes an event, and broadcasts the
// condition.
// Returns false if the task was not found or already in a terminal state (idempotent).
// Must be called with m.mu held.
func (m *Manager) finalize(id string, apply func(rec *taskRecord)) bool {
	rec, ok := m.tasks[id]
	if !ok || taskDone(rec.doneCh) {
		return false
	}

	now := time.Now()
	rec.task.DoneAt = &now
	apply(rec)

	// Signal per-task waiters (Wait) and the all-done waiters (Close).
	close(rec.doneCh)
	m.sendEventLocked(rec, eventTypeForStatus(rec.task.Status))
	m.cond.Broadcast()
	return true
}

// sendEventLocked publishes a task event to subscribers, if Subscribe has
// been called. Must be called with m.mu held.
func (m *Manager) sendEventLocked(rec *taskRecord, typ TaskEventType) {
	if typ != "" && m.eventBuf != nil {
		m.eventBuf.TrySend(&TaskEvent{Type: typ, Task: cloneTask(&rec.task)})
	}
}

func eventTypeForStatus(status Status) TaskEventType {
	switch status {
	case StatusCompleted:
		return TaskEventCompleted
	case StatusFailed:
		return TaskEventFailed
	case StatusCanceled:
		return TaskEventCanceled
	default:
		return ""
	}
}

// cloneTask returns a copy of t safe to hand to callers. The Metadata map is
// shallow-copied so callers cannot mutate the registry's map entries, though
// mutable values stored inside Metadata remain shared.
func cloneTask(t *Task) *Task {
	clone := *t
	clone.Metadata = cloneMetadata(t.Metadata)
	return &clone
}

func (m *Manager) hasRunningLocked() bool {
	for _, rec := range m.tasks {
		if !taskDone(rec.doneCh) {
			return true
		}
	}
	return false
}

func taskDone(doneCh <-chan struct{}) bool {
	select {
	case <-doneCh:
		return true
	default:
		return false
	}
}

// TaskInfo is a read-only snapshot of the facts the Manager establishes about a
// task at creation, handed to the WorkFunc when it starts. It is not the live
// Task record: it carries only identity fixed at creation, never the mutable
// lifecycle fields (Result/Status/Error/OutputFileErr) the Manager fills later,
// so work never races on them. The work already holds everything the launcher
// passed in (Type, OutputFile, Metadata, ...); TaskInfo supplies what only the
// Manager knows. New fields may be added over time — adding a field is backward
// compatible, so the WorkFunc signature stays stable.
type TaskInfo struct {
	// ID is the Manager-generated task id. It is the one fact the work cannot
	// otherwise obtain: the id is assigned inside createTask, after the work
	// closure is already built. The launcher passes it to MarkOutputFileUnreliable
	// to report an output-file write failure against this task.
	ID string
	// Backgrounded is closed when this task moves to background execution: before
	// the work starts for an explicit RunInBackground launch, or at the
	// auto-background transition (foreground deadline reached and permitted). It
	// stays open for a run that completes in the foreground. Work uses it to stop
	// side effects that are only valid while the run is foreground — most notably
	// forwarding events to the launching turn's live stream, which the turn closes
	// once it ends. It is never nil.
	Backgrounded <-chan struct{}
}

// WorkFunc performs a single managed execution. It is supplied by the caller
// (e.g. a subagent or filesystem adapter); the Manager itself never knows what
// the work is.
//
// task carries the Manager-assigned facts about this run (see TaskInfo) — most
// importantly its id, which the work needs to report an output-file write failure
// via Manager.MarkOutputFileUnreliable.
//
// ctx carries the values of the Run call's context but is detached from its
// cancellation, so a backgrounded task outlives the turn that launched it. It is
// canceled when Cancel is invoked for this task, when a foreground deadline or an
// abandoned foreground wait stops it, or when the Manager is closed. Work should
// honor it.
//
// The returned result becomes Task.Result; a non-nil err becomes Task.Error and
// transitions the task to StatusFailed.
type WorkFunc func(ctx context.Context, task TaskInfo) (result string, err error)

// detachedCtx carries its parent's values but is never canceled by the parent.
// It mirrors context.WithoutCancel (Go 1.21+); this package targets Go 1.18.
// Background work runs under a detachedCtx (wrapped by a fresh cancelable context)
// so it survives cancellation of the per-turn context that launched it, while
// still seeing that context's values.
type detachedCtx struct{ parent context.Context }

func (detachedCtx) Deadline() (deadline time.Time, ok bool) { return time.Time{}, false }

func (detachedCtx) Done() <-chan struct{} { return nil }

func (detachedCtx) Err() error { return nil }

func (c detachedCtx) Value(key any) any { return c.parent.Value(key) }

// Run executes work as a managed task on m.
//
// The execution mode depends on input.RunInBackground and the effective foreground
// timeout (input.ForegroundTimeoutMs if set, else the Manager's configured default):
//   - Foreground (RunInBackground=false, timeout<=0): blocks until completion
//   - Background (RunInBackground=true): returns an initial StatusRunning snapshot
//     without waiting for work. The task may complete immediately afterward; use
//     Get or task events to observe its current state.
//   - Deadline (timeout>0): runs in foreground up to the timeout, then — if still
//     running — consults the Manager's ShouldAutoBackground hook. If it permits,
//     the run is moved to the background (kept running) and Run returns
//     StatusRunning. Otherwise the run is canceled and reported as timed out
//     (StatusFailed).
//
// All runs are tracked in Manager state and visible via Get/List.
func (m *Manager) Run(ctx context.Context, input *RunInput, work WorkFunc) (*Task, error) {
	id, err := m.createTask(ctx, input)
	if err != nil {
		return nil, err
	}

	// The work runs under a context detached from the caller's (per-turn)
	// cancellation, so a backgrounded task is not killed when the turn that
	// launched it ends or is preempted. The caller ctx's values are preserved
	// (framework/session state the work relies on); only its cancellation is
	// dropped. The work is stopped by Cancel(id), the foreground deadline, an
	// abandoned foreground wait (caller ctx canceled), or Close.
	runCtx, cancel := context.WithCancel(detachedCtx{parent: ctx})
	m.storeCancelFunc(id, cancel)

	bgCh := m.backgroundedCh(id)

	// run executes the work and finalizes the task. The terminal outcome lives on
	// the task record (set by completeTask/failTask), which Run reads back via
	// taskSnapshot — so run signals completion rather than returning a value.
	run := func() {
		defer cancel()
		defer func() {
			if p := recover(); p != nil {
				// A panicking WorkFunc must fail its own task, not crash the process.
				m.failTask(id, safe.NewPanicErr(p, debug.Stack()))
			}
		}()
		r, runErr := work(runCtx, TaskInfo{ID: id, Backgrounded: bgCh})
		if runErr != nil {
			m.failTask(id, runErr)
		} else {
			m.completeTask(id, r)
		}
	}

	// Explicit background: run in goroutine, return immediately. createTask already
	// marked the task RunInBackground; signal backgrounded before the work starts so
	// the work never treats itself as foreground.
	if input.RunInBackground {
		m.markBackgrounded(id)
		task := m.taskSnapshot(id)
		go run()
		return task, nil
	}

	// Foreground: run in a goroutine and wait. The wait honors caller cancellation
	// (the detached work ctx does not, so it is canceled explicitly here) and, when a
	// timeout is set, the foreground deadline.
	done := make(chan struct{}, 1)
	go func() { run(); done <- struct{}{} }()

	foregroundTimeoutMs := m.foregroundTimeoutMs
	if input.ForegroundTimeoutMs != nil {
		foregroundTimeoutMs = *input.ForegroundTimeoutMs
	}

	if foregroundTimeoutMs > 0 {
		// Foreground with a deadline: wait up to the effective timeout (per-run
		// override takes precedence over the Manager default). On the deadline,
		// either move to the background (if the hook permits) or cancel as timed out.
		timer := time.NewTimer(time.Duration(foregroundTimeoutMs) * time.Millisecond)
		defer timer.Stop()
		select {
		case <-done:
			// run() has already finalized the task before signaling, so the recorded
			// state is authoritative — including a StatusCanceled set by a concurrent
			// Cancel, which must win over the work's own ctx-canceled error.
			return m.taskSnapshot(id), nil
		case <-ctx.Done():
			// Caller abandoned the foreground wait before the deadline (e.g. the
			// turn was canceled) and before any auto-background: stop the work.
			m.cancelIfRunning(id)
			return m.taskSnapshot(id), nil
		case <-timer.C:
			task, ok := m.Get(id)
			if !ok || task.DoneAt != nil {
				// Work finished right at the deadline — report its actual outcome.
				return m.taskSnapshot(id), nil
			}
			if m.allowAutoBackground(ctx, task) && m.detach(id) {
				return m.taskSnapshot(id), nil
			}
			// Hook declined (or work finished during the hook): stop if still running.
			m.timeoutTask(id, foregroundTimeoutMs)
			return m.taskSnapshot(id), nil
		}
	}

	// Foreground without a deadline: block until completion or caller cancellation.
	select {
	case <-done:
		return m.taskSnapshot(id), nil
	case <-ctx.Done():
		m.cancelIfRunning(id)
		return m.taskSnapshot(id), nil
	}
}

// StreamWorkFunc performs a single managed streaming execution. It is the
// streaming counterpart of WorkFunc: instead of returning the whole result at
// once, it returns a stream of output chunks. The Manager forwards those chunks
// to the RunStream caller in real time and, in parallel, accumulates them into
// the task's final Result (and OutputFile). Chunk semantics (formatting, exit
// codes) are entirely the caller's concern; the Manager only concatenates.
//
// task behaves exactly as for WorkFunc (see TaskInfo): it carries the task id the
// work uses to report an output-file write failure.
//
// ctx behaves exactly as for WorkFunc (see WorkFunc): detached from the caller's
// cancellation, stopped by Cancel/deadline/Close. Work should honor it and close
// the returned reader when ctx is done.
//
// Return the reader promptly. The Manager's foreground timeout and
// RunInput.BackgroundStartupPreviewMs windows are measured from when this function
// returns its reader, not from the RunStream call — RunStream calls it synchronously
// and only starts those timers afterward. So blocking initialization (spawning a
// process, waiting for a subprocess to be ready, dialing) must be done in the
// producer goroutine that writes to the reader and surfaced as its first chunks, not
// before returning. Work that blocks before returning makes the caller wait for
// init-time plus the window rather than the window alone, and that extra wait is not
// bounded by either timeout.
type StreamWorkFunc func(ctx context.Context, task TaskInfo) (*schema.StreamReader[string], error)

// RunStream executes streaming work as a managed task, returning a stream of
// output chunks to consume in real time.
//
// It mirrors Run's lifecycle (tracking, foreground timeout, auto-background) but
// preserves streaming for the foreground phase:
//   - Foreground completion: every chunk is forwarded live, then the stream closes.
//   - Auto-background at the deadline: chunks forwarded so far are kept; the
//     Manager appends a single notice chunk (task id + output file) and closes the
//     caller's stream, while the work keeps running in the background — its
//     remaining output is drained into the task's Result/OutputFile.
//   - Explicit background (input.RunInBackground): the work runs detached from the
//     start. By default no execution chunks reach the caller; when
//     input.BackgroundStartupPreviewMs is positive, chunks emitted during that
//     bounded startup window are forwarded. If work finishes during the preview,
//     all chunks are forwarded and the stream closes with no background notice.
//     Otherwise the notice ends the preview and the remaining output is drained
//     into the task's Result/OutputFile.
//
// The foreground and preview windows are both measured from when the work returns
// its stream reader (see StreamWorkFunc), not from this call: RunStream's forwarding
// goroutine starts the timers only after work returns its reader. Blocking
// initialization performed before the reader is returned is therefore not counted
// against either window — streaming work must return its reader promptly for the
// windows to reflect output time rather than startup time.
//
// The returned reader is always non-nil on a nil error. The Manager is the sole
// writer of that stream, so there is never a write race with the work.
func (m *Manager) RunStream(ctx context.Context, input *RunInput, work StreamWorkFunc) (*schema.StreamReader[string], error) {
	id, err := m.createTask(ctx, input)
	if err != nil {
		return nil, err
	}

	runCtx, cancel := context.WithCancel(detachedCtx{parent: ctx})
	m.storeCancelFunc(id, cancel)

	sr, sw := schema.Pipe[string](streamBufferCap)

	foregroundTimeoutMs := m.foregroundTimeoutMs
	if input.ForegroundTimeoutMs != nil {
		foregroundTimeoutMs = *input.ForegroundTimeoutMs
	}
	// An explicit background launch has no foreground phase to stream, so its
	// foreground timeout is irrelevant: forward nothing, just emit the notice.
	if input.RunInBackground {
		foregroundTimeoutMs = 0
	}

	go m.forwardStream(&streamRun{
		callerCtx:           ctx,
		runCtx:              runCtx,
		cancel:              cancel,
		id:                  id,
		input:               input,
		work:                work,
		sw:                  sw,
		foregroundTimeoutMs: foregroundTimeoutMs,
	})
	return sr, nil
}

// streamRun bundles the per-run state for forwardStream (kept as one value to stay
// within the argument limit and to make the goroutine launch self-documenting).
type streamRun struct {
	callerCtx           context.Context
	runCtx              context.Context
	cancel              context.CancelFunc
	id                  string
	input               *RunInput
	work                StreamWorkFunc
	sw                  *schema.StreamWriter[string]
	foregroundTimeoutMs int
}

// forwardStream owns the caller-facing stream writer sw: it is the only goroutine
// that writes to it, so injecting the background notice never races the work.
func (m *Manager) forwardStream(r *streamRun) {
	defer r.cancel()
	// A panic constructing the work stream (r.work below) lands here, before sw is
	// closed: fail the task and surface it on the caller stream. Panics while reading
	// chunks are recovered closer to their source — pumpStream for the foreground
	// and preview loops, drainReader for the direct background drain — so this never
	// double-closes sw.
	defer func() {
		if p := recover(); p != nil {
			err := safe.NewPanicErr(p, debug.Stack())
			m.failTask(r.id, err)
			r.sw.Send("", err)
			r.sw.Close()
		}
	}()

	// Explicit background: the run is background from the start, so signal it before
	// the work starts (RunStream forces foregroundTimeoutMs=0 for this case).
	if r.input.RunInBackground {
		m.markBackgrounded(r.id)
	}

	ws, err := r.work(r.runCtx, TaskInfo{ID: r.id, Backgrounded: m.backgroundedCh(r.id)})
	if err != nil {
		m.failTask(r.id, err)
		r.sw.Send("", err)
		r.sw.Close()
		return
	}
	defer ws.Close()

	var buf strings.Builder

	// Explicit background: the lifecycle is already detached, but a caller may opt
	// into a bounded startup preview so launch-time output (for example an OAuth
	// URL) remains visible. After the preview, or immediately when it is disabled,
	// cap the caller stream with a notice and drain the rest into the result.
	if r.input.RunInBackground {
		if r.input.BackgroundStartupPreviewMs <= 0 {
			r.sw.Send(m.backgroundStartNotice(r.runCtx, r.id), nil)
			r.sw.Close()
			m.drainReader(r.id, ws, &buf)
			return
		}
		m.forwardPumpedStream(r, ws, &buf, pumpedStreamBackgroundPreview)
		return
	}

	m.forwardPumpedStream(r, ws, &buf, pumpedStreamForeground)
}

// pumpedStreamMode describes the caller-visible phase handled by
// forwardPumpedStream. Both modes need pumpStream so they can select on blocking
// work output together with a timer and caller cancellation. Explicit background
// runs without a preview bypass this path and use drainReader directly.
type pumpedStreamMode uint8

const (
	pumpedStreamForeground pumpedStreamMode = iota
	pumpedStreamBackgroundPreview
)

// forwardPumpedStream forwards chunks during a foreground or explicit-background
// preview phase. The chunk, completion, and error paths are shared; only caller
// abandonment and timer expiry have mode-specific lifecycle semantics.
func (m *Manager) forwardPumpedStream(r *streamRun, ws *schema.StreamReader[string], buf *strings.Builder, mode pumpedStreamMode) {
	chunks := pumpStream(r.runCtx, ws)

	var timerC <-chan time.Time
	phaseTimeoutMs := r.foregroundTimeoutMs
	if mode == pumpedStreamBackgroundPreview {
		phaseTimeoutMs = r.input.BackgroundStartupPreviewMs
	}
	if phaseTimeoutMs > 0 {
		timer := time.NewTimer(time.Duration(phaseTimeoutMs) * time.Millisecond)
		defer timer.Stop()
		timerC = timer.C
	}

	for {
		select {
		case c := <-chunks:
			if c.err == io.EOF {
				m.completeTask(r.id, buf.String())
				r.sw.Close()
				return
			}
			if c.err != nil {
				m.failTask(r.id, c.err)
				r.sw.Send("", c.err)
				r.sw.Close()
				return
			}
			buf.WriteString(c.text)
			if r.sw.Send(c.text, nil) {
				if mode == pumpedStreamBackgroundPreview {
					// The caller stopped reading the preview. The task was explicitly
					// backgrounded, so keep it running and drain the remaining output.
					r.sw.Close()
					m.drainStream(r.runCtx, r.id, chunks, buf)
					return
				}
				// Caller closed a foreground stream early: stop the work.
				m.cancelIfRunning(r.id)
				return
			}
		case <-r.callerCtx.Done():
			if mode == pumpedStreamBackgroundPreview {
				// Caller cancellation does not stop an explicitly backgrounded task.
				// Stop previewing and keep draining under the detached run context.
				r.sw.Close()
				m.drainStream(r.runCtx, r.id, chunks, buf)
				return
			}
			// Caller abandoned the foreground wait before the deadline: stop work.
			m.cancelIfRunning(r.id)
			r.sw.Close()
			return
		case <-timerC:
			if mode == pumpedStreamBackgroundPreview {
				r.sw.Send(m.backgroundStartNotice(r.runCtx, r.id), nil)
				r.sw.Close()
				m.drainStream(r.runCtx, r.id, chunks, buf)
				return
			}
			task, ok := m.Get(r.id)
			if !ok || task.DoneAt != nil {
				continue // finished right at the deadline; let the chunks case end it
			}
			if m.allowAutoBackground(r.callerCtx, task) && m.detach(r.id) {
				// Moved to the background: cap the caller's stream with a notice and
				// keep draining the rest into the task result.
				r.sw.Send(m.backgroundMoveNotice(r.runCtx, r.id), nil)
				r.sw.Close()
				m.drainStream(r.runCtx, r.id, chunks, buf)
				return
			}
			m.timeoutTask(r.id, r.foregroundTimeoutMs)
			r.sw.Close()
			return
		}
	}
}

// streamChunk is one item pumped off a StreamWorkFunc's reader: either a piece of
// output text or a terminal error (io.EOF on normal completion).
type streamChunk struct {
	text string
	err  error
}

// pumpStream turns a stream reader's blocking Recv loop into a channel, so the
// forward loop can wait on output alongside the deadline and caller cancellation.
// It stops when ctx is done (the run was canceled, timed out, or closed).
func pumpStream(ctx context.Context, ws *schema.StreamReader[string]) <-chan streamChunk {
	chunks := make(chan streamChunk)
	go func() {
		// ws.Recv runs the work's stream (including any convert step) in this
		// goroutine, so a panic there must not crash the process. Turn it into a
		// terminal chunk error; the forward loop fails the task on it like any other.
		defer func() {
			if p := recover(); p != nil {
				select {
				case chunks <- streamChunk{err: safe.NewPanicErr(p, debug.Stack())}:
				case <-ctx.Done():
				}
			}
		}()
		for {
			text, err := ws.Recv()
			c := streamChunk{text: text, err: err}
			select {
			case chunks <- c:
			case <-ctx.Done():
				return
			}
			if err != nil {
				return
			}
		}
	}()
	return chunks
}

// drainReader consumes a backgrounded run's reader directly into buf and finalizes
// the task on completion. Used by the explicit-background path, which has no
// foreground select loop and therefore no pumpStream channel — reading ws inline
// saves a goroutine. Called after the caller's stream has been closed, so it never
// writes to sw.
//
// Unlike drainStream it has no runCtx.Done() case: it exits only when ws.Recv
// returns EOF or an error. On Cancel/Close the run's ctx is canceled, which the
// work must honor by ending its stream — that is what unblocks Recv here. A no-op
// completeTask/failTask then loses the race against the cancelTask that already
// finalized the task (both are idempotent). This mirrors the original drainStream,
// whose pump goroutine likewise stayed blocked on Recv until the work honored ctx.
func (m *Manager) drainReader(id string, ws *schema.StreamReader[string], buf *strings.Builder) {
	// ws.Recv runs the work's stream in this goroutine; a panic must fail the task,
	// not crash the process. The caller stream is already closed before draining, so
	// recovery only finalizes — it never touches sw.
	defer func() {
		if p := recover(); p != nil {
			m.failTask(id, safe.NewPanicErr(p, debug.Stack()))
		}
	}()
	for {
		text, err := ws.Recv()
		if err == io.EOF {
			m.completeTask(id, buf.String())
			return
		}
		if err != nil {
			m.failTask(id, err)
			return
		}
		buf.WriteString(text)
	}
}

// drainStream consumes a backgrounded run's remaining chunks into buf and
// finalizes the task on completion. Called after the caller's stream has been
// closed, so it never writes to sw.
func (m *Manager) drainStream(runCtx context.Context, id string, chunks <-chan streamChunk, buf *strings.Builder) {
	for {
		select {
		case c := <-chunks:
			if c.err == io.EOF {
				m.completeTask(id, buf.String())
				return
			}
			if c.err != nil {
				m.failTask(id, c.err)
				return
			}
			buf.WriteString(c.text)
		case <-runCtx.Done():
			// The run was canceled/closed while backgrounded; finalize already
			// happened via cancelTask, so just stop draining.
			return
		}
	}
}

// backgroundStartNotice builds the chunk emitted for an explicit RunInBackground
// launch.
func (m *Manager) backgroundStartNotice(ctx context.Context, id string) string {
	return m.notice(ctx, id, false)
}

// backgroundMoveNotice builds the chunk appended when a foreground run is moved to
// the background by the auto-background policy.
func (m *Manager) backgroundMoveNotice(ctx context.Context, id string) string {
	return m.notice(ctx, id, true)
}

// notice produces the background-launch chunk: the configured BackgroundNotice
// hook when set, otherwise defaultBackgroundNotice. It snapshots the task so the
// hook sees the same lifecycle facts (id, type, output file) the default would.
func (m *Manager) notice(ctx context.Context, id string, autoBackgrounded bool) string {
	task, _ := m.Get(id)
	info := NoticeInfo{Task: task, AutoBackgrounded: autoBackgrounded}
	if m.backgroundNoticeFn != nil {
		return m.backgroundNoticeFn(ctx, info)
	}
	return defaultBackgroundNotice(info)
}

// noticeTemplate is the default background-notice text. Placeholders are filled by
// defaultBackgroundNotice; {kind} and {output} expand to empty when absent, so the
// same template serves the with- and without-output-file cases.
const noticeTemplate = "\n[task {id}{kind} {state}; you will be notified when it completes.{output}]"

// noticeOutputTemplate is the {output} fragment, present only when the task has a
// reserved output file.
const noticeOutputTemplate = " Output is being written to: {file}." +
	" To check interim output, use Read on that file path."

// defaultBackgroundNotice is the built-in BackgroundNotice. It announces the
// background launch and, when an output file is reserved, directs the reader to
// Read that path for interim output. It deliberately names no control tool, since
// the retrieval mechanism is host-specific (see Config.BackgroundNotice).
func defaultBackgroundNotice(info NoticeInfo) string {
	id, kind, outputFile := "", "", ""
	if info.Task != nil {
		id = info.Task.ID
		if info.Task.Type != "" {
			kind = " (" + info.Task.Type + ")"
		}
		outputFile = info.Task.OutputFile
	}

	state := "is running in the background"
	if info.AutoBackgrounded {
		state = "moved to the background"
	}

	output := ""
	if outputFile != "" {
		output = strings.NewReplacer("{file}", outputFile).Replace(noticeOutputTemplate)
	}

	return strings.NewReplacer(
		"{id}", id,
		"{kind}", kind,
		"{state}", state,
		"{output}", output,
	).Replace(noticeTemplate)
}

// streamBufferCap is the buffer size of the caller-facing stream pipe.
const streamBufferCap = 16

// taskSnapshot returns the current state of a task as a cloned *Task. The task
// record is the single source of truth, so a concurrent cancel or timeout is
// reflected faithfully. It falls back to a minimal failed snapshot if the task is
// somehow absent (should not happen for a just-created task).
func (m *Manager) taskSnapshot(id string) *Task {
	if task, ok := m.Get(id); ok {
		return task
	}
	return &Task{ID: id, Status: StatusFailed}
}
