/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package adk

import "context"

// RunnerMiddleware provides hooks to customize runner and agent behavior at various stages of execution.
type RunnerMiddleware struct {
	// Name of the middleware, default empty. This will be used for middleware deduplication.
	Name string

	// BeforeRunner is called before the runner starts executing. It allows modifying the context
	// or performing any setup actions before the agent begins processing.
	// When an error is returned:
	// 1. The framework will immediately return an AsyncIterator containing only this error
	// 2. Subsequent BeforeRunner steps in other middlewares will be interrupted
	// 3. The OnEvents handlers in previously executed middlewares will be invoked
	BeforeRunner func(ctx context.Context, rc *RunnerContext) (nextContext context.Context, err error)

	// OnEvents is called to handle events generated by the agent inside runner during execution.
	// - iter: The iterator contains the original output from the agent or the processed output from the previous middlewares.
	// - gen: The generator is used to send the processed events to the next middleware or directly as output.
	// This allows for filtering, transforming, or adding events in the middleware chain.
	OnEvents func(ctx context.Context, rc *RunnerContext, iter *AsyncIterator[*AgentEvent], gen *AsyncGenerator[*AgentEvent])

	// GlobalAgentMiddleware is an optional middleware that, if set,
	// will be prepended to the middleware chain of every Agent running under this Runner.
	GlobalAgentMiddleware *AgentMiddleware
}

type RunnerContext struct {
	Messages        []Message
	AgentRunOptions []AgentRunOption

	// internal properties, read only
	agentName    string
	entrance     EntranceType
	checkpointID *string
}

func (r *RunnerContext) AgentName() string {
	return r.agentName
}

func (r *RunnerContext) EntranceType() EntranceType {
	return r.entrance
}

func (r *RunnerContext) CheckpointID() *string {
	return r.checkpointID
}

type runnerMWHelper struct {
	beforeRunnerFns []func(ctx context.Context, rc *RunnerContext) (nextContext context.Context, err error)
	onEventsFns     []func(ctx context.Context, rc *RunnerContext, iter *AsyncIterator[*AgentEvent], gen *AsyncGenerator[*AgentEvent])
}

func (r *runnerMWHelper) execBeforeRunner(ctx context.Context, rc *RunnerContext) (context.Context, *AsyncIterator[*AgentEvent]) {
	var err error
	for i, beforeRunner := range r.beforeRunnerFns {
		if beforeRunner == nil {
			continue
		}
		ctx, err = beforeRunner(ctx, rc)
		if err != nil {
			iter, gen := NewAsyncIteratorPair[*AgentEvent]()
			gen.Send(&AgentEvent{Err: err})
			gen.Close()
			return ctx, r.execOnEventsFromIndex(ctx, rc, i-1, iter)
		}
	}
	return ctx, nil
}

func (r *runnerMWHelper) execOnEvents(ctx context.Context, rc *RunnerContext, iter *AsyncIterator[*AgentEvent]) *AsyncIterator[*AgentEvent] {
	return r.execOnEventsFromIndex(ctx, rc, len(r.onEventsFns)-1, iter)
}

func (r *runnerMWHelper) execOnEventsFromIndex(ctx context.Context, rc *RunnerContext, fromIdx int, iter *AsyncIterator[*AgentEvent]) *AsyncIterator[*AgentEvent] {
	for idx := fromIdx; idx >= 0; idx-- {
		onEvents := r.onEventsFns[idx]
		if onEvents == nil {
			continue
		}
		i, g := NewAsyncIteratorPair[*AgentEvent]()
		onEvents(ctx, rc, iter, g)
		iter = i
	}
	return iter
}
