/*
 * Copyright 2026 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package subagent

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"sync"
	"time"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/internal"
	"github.com/cloudwego/eino/schema"
)

// Status represents the lifecycle status of a task.
type Status string

const (
	// StatusRunning indicates the task is currently executing.
	StatusRunning Status = "running"
	// StatusCompleted indicates the task finished successfully.
	StatusCompleted Status = "completed"
	// StatusFailed indicates the task terminated with an error.
	StatusFailed Status = "failed"
	// StatusCanceled indicates the task was canceled by an external request.
	StatusCanceled Status = "canceled"
)

// Task represents a single agent execution record.
type Task struct {
	// ID is the unique identifier for this task, generated by TaskMgr.
	ID string
	// Description is a human-readable summary of what the task does.
	Description string
	// Status is the current lifecycle status.
	Status Status
	// Result contains the task output, set when Status is StatusCompleted.
	Result string
	// Error contains the error message, set when Status is StatusFailed.
	Error string
	// RunInBackground indicates whether this task was launched in background mode.
	// This helps distinguish background tasks from foreground ones
	// when inspecting task state after WaitAllDone.
	RunInBackground bool
	// ResultQueried indicates whether the main agent has queried this task's result
	// via the TaskOutput tool. This helps developers know which background task
	// results have already been consumed by the orchestrating agent.
	ResultQueried bool
	// CreatedAt is the time the task was registered.
	CreatedAt time.Time
	// DoneAt is the time the task reached a terminal state. Nil if still running.
	DoneAt *time.Time
	// Metadata holds arbitrary extensible fields for future use.
	Metadata map[string]any
}

// Notification is emitted when a task's status changes.
// It is the default *schema.Message specialization of TypedNotification.
type Notification = TypedNotification[*schema.Message]

// TypedNotification is emitted when a task's status changes.
// A running notification includes an Events iterator for streaming agent events.
// Terminal notifications (completed, failed, canceled) contain the final task state.
type TypedNotification[M adk.MessageType] struct {
	// Task contains the current state of the task at the time of notification.
	Task *Task
	// Events is an async iterator over the running task's agent events
	// (not a schema.StreamReader). Non-nil only when Task.Status is StatusRunning.
	// The iterator is closed automatically when the task reaches a terminal state.
	Events *adk.AsyncIterator[*adk.TypedAgentEvent[M]]
}

// RunResult is the return value of TaskMgr.Run.
// It reports the outcome of a run so the caller does not need to track the task itself.
type RunResult struct {
	// TaskID is the unique identifier assigned to this execution.
	TaskID string
	// Status indicates the outcome: StatusCompleted, StatusFailed, or StatusRunning (for background tasks).
	Status Status
	// Result is the agent's output when Status is StatusCompleted.
	Result string
	// Error is the error message when Status is StatusFailed.
	Error string
}

// RunInput is the input for TaskMgr.Run.
// Using a struct instead of positional arguments for extensibility (e.g., future interrupt/resume fields).
type RunInput struct {
	// SubagentType is the name of the registered agent to execute.
	SubagentType string
	// Prompt is the task content passed to the agent as its input.
	Prompt string
	// Description is a short human-readable title for the task, stored in Task.Description.
	Description string
	// RunInBackground controls execution mode: true returns immediately with StatusRunning.
	RunInBackground bool
}

// defaultAutoBackgroundMs is the default auto-background timeout (120 seconds).
const defaultAutoBackgroundMs = 120_000

// TaskMgrConfig configures a TaskMgr.
type TaskMgrConfig struct {
	// AutoBackgroundMs sets the automatic foreground-to-background switching timeout.
	// When > 0, a foreground agent run that hasn't completed within this many
	// milliseconds will automatically switch to background mode.
	// When 0, auto-background is disabled (foreground runs block indefinitely).
	//
	// Default: 120000ms (120 seconds).
	AutoBackgroundMs *int
}

// TaskMgr manages the lifecycle of sub-agent executions for the standard
// *schema.Message message type. It is the default specialization of TypedTaskMgr.
type TaskMgr = TypedTaskMgr[*schema.Message]

// NewTaskMgr creates a new TaskMgr for managing *schema.Message sub-agent task lifecycles.
// By default, auto-background is enabled with a 120-second timeout.
// Set AutoBackgroundMs to 0 to disable it.
func NewTaskMgr(ctx context.Context, conf *TaskMgrConfig) *TaskMgr {
	return NewTypedTaskMgr[*schema.Message](ctx, conf)
}

// NewTypedTaskMgr creates a new TypedTaskMgr for managing sub-agent task lifecycles.
// By default, auto-background is enabled with a 120-second timeout.
// Set AutoBackgroundMs to 0 to disable it.
func NewTypedTaskMgr[M adk.MessageType](_ context.Context, conf *TaskMgrConfig) *TypedTaskMgr[M] {
	m := &TypedTaskMgr[M]{
		tasks:            make(map[string]*typedTaskRecord[M]),
		autoBackgroundMs: defaultAutoBackgroundMs,
	}
	m.cond = sync.NewCond(&m.mu)
	if conf.AutoBackgroundMs != nil {
		m.autoBackgroundMs = *conf.AutoBackgroundMs
	}
	return m
}

// TypedTaskMgr manages the lifecycle of sub-agent executions.
// It owns both the execution (Run) and the state tracking (Get/List/Cancel).
//
// TypedTaskMgr is Agent-aware: it maintains a registry of agents (via RegisterAgent),
// resolves them by name in Run, and manages foreground/background/auto-background
// switching internally. Agents are executed via adk.TypedRunner.Query, which handles
// the agent lifecycle without needing to wrap agents as tools.
type TypedTaskMgr[M adk.MessageType] struct {
	mu               sync.Mutex
	cond             *sync.Cond
	tasks            map[string]*typedTaskRecord[M]
	agents           map[string]adk.TypedAgent[M] // agent registry: name → Agent
	seq              int64
	closed           bool
	autoBackgroundMs int

	// Subscription fields, initialized lazily by Subscribe().
	subscribeOnce sync.Once
	notifyCh      chan *TypedNotification[M]
	notifyBuf     *internal.UnboundedChan[*TypedNotification[M]]
}

type typedTaskRecord[M adk.MessageType] struct {
	task     Task
	cancel   adk.AgentCancelFunc
	done     bool                                         // true once task reaches a terminal state
	eventGen *adk.AsyncGenerator[*adk.TypedAgentEvent[M]] // closed on terminal state
}

// runResult carries the result from a goroutine running the sub-agent.
type runResult struct {
	result string
	err    error
}

// RegisterAgent adds an agent to the TaskMgr registry.
// Agents must be registered before they can be referenced by SubagentType in RunInput.
// Typically called during middleware initialization.
func (m *TypedTaskMgr[M]) RegisterAgent(name string, agent adk.TypedAgent[M]) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.agents == nil {
		m.agents = make(map[string]adk.TypedAgent[M])
	}
	m.agents[name] = agent
}

// Run executes a registered agent as a managed task.
//
// The agent is resolved by input.SubagentType from the internal registry (see RegisterAgent).
// Execution uses adk.TypedRunner.Query to run the agent directly, without wrapping it as a tool.
//
// The execution mode depends on input.RunInBackground and TaskMgr configuration:
//   - Foreground (RunInBackground=false, autoBackgroundMs=0): blocks until completion
//   - Background (RunInBackground=true): returns immediately with StatusRunning
//   - AutoBackground (autoBackgroundMs>0): foreground with timeout, auto-switches to background
//
// All runs are tracked in TaskMgr state and visible via Get/List/Notifications.
func (m *TypedTaskMgr[M]) Run(ctx context.Context, input *RunInput) (*RunResult, error) {
	agent, ok := m.getAgent(input.SubagentType)
	if !ok {
		return nil, fmt.Errorf("subagent: agent %q not registered in TaskMgr", input.SubagentType)
	}

	id, eventGen, err := m.createTask(input.Description, input.RunInBackground)
	if err != nil {
		return nil, err
	}

	// Set up cancel support. The AgentRunOption is passed to Runner.Query,
	// and the AgentCancelFunc is stored so Cancel() can invoke it.
	cancelOpt, cancelFn := adk.WithCancel()
	m.storeCancelFunc(id, cancelFn)

	run := func() runResult {
		runner := adk.NewTypedRunner[M](adk.TypedRunnerConfig[M]{Agent: agent})
		iter := runner.Query(ctx, input.Prompt, cancelOpt)
		r, runErr := drainEvents(iter, eventGen)
		if runErr != nil {
			m.failTask(id, runErr)
		} else {
			m.completeTask(id, r)
		}
		return runResult{r, runErr}
	}

	// Explicit background: run in goroutine, return immediately.
	if input.RunInBackground {
		go run()
		return &RunResult{TaskID: id, Status: StatusRunning}, nil
	}

	// Auto-background: run in goroutine, wait with timeout, then switch to background.
	if m.autoBackgroundMs > 0 {
		resultCh := make(chan runResult, 1)
		go func() { resultCh <- run() }()
		select {
		case r := <-resultCh:
			return m.toRunResult(id, r), nil
		case <-time.After(time.Duration(m.autoBackgroundMs) * time.Millisecond):
			return &RunResult{TaskID: id, Status: StatusRunning}, nil
		}
	}

	// Foreground: run inline, no goroutine needed.
	r := run()
	return m.toRunResult(id, r), nil
}

func (m *TypedTaskMgr[M]) toRunResult(id string, r runResult) *RunResult {
	if r.err != nil {
		return &RunResult{TaskID: id, Status: StatusFailed, Error: r.err.Error()}
	}
	return &RunResult{TaskID: id, Status: StatusCompleted, Result: r.result}
}

// Get returns the current state of a task by ID.
// Returns (nil, false) if the task does not exist.
func (m *TypedTaskMgr[M]) Get(id string) (*Task, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return nil, false
	}
	clone := rec.task
	return &clone, true
}

// MarkQueried marks a task's result as having been queried by the main agent
// (typically via the TaskOutput tool). This helps developers know which
// background task results have already been consumed by the orchestrating agent.
func (m *TypedTaskMgr[M]) MarkQueried(id string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.task.ResultQueried = true
	}
}

// List returns a snapshot of all tasks (both running and completed).
func (m *TypedTaskMgr[M]) List() []*Task {
	m.mu.Lock()
	defer m.mu.Unlock()

	tasks := make([]*Task, 0, len(m.tasks))
	for _, rec := range m.tasks {
		clone := rec.task
		tasks = append(tasks, &clone)
	}
	return tasks
}

// Cancel stops a running task. The agent's cancel function will be invoked,
// and the task will transition to StatusCanceled.
// Returns an error if the task does not exist or is not running.
func (m *TypedTaskMgr[M]) Cancel(id string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	rec, ok := m.tasks[id]
	if !ok {
		return fmt.Errorf("subagent: task %q not found", id)
	}
	if rec.done {
		return fmt.Errorf("subagent: task %q is not running (status: %s)", id, rec.task.Status)
	}

	m.cancelTask(rec)
	return nil
}

// Subscribe returns a channel that receives a Notification each time a task
// reaches a terminal state (completed, failed, or canceled).
//
// Subscribe uses a subscription model: only notifications generated after the
// subscription is created will be delivered. To query the state of tasks that
// completed before subscribing, use Get or List.
//
// The returned channel is closed when TaskMgr.Close is called.
// Subscribe must be called before starting tasks to avoid missing notifications.
// Multiple calls return the same channel.
func (m *TypedTaskMgr[M]) Subscribe() <-chan *TypedNotification[M] {
	m.subscribeOnce.Do(func() {
		m.notifyBuf = internal.NewUnboundedChan[*TypedNotification[M]]()
		m.notifyCh = make(chan *TypedNotification[M])
		go m.relayNotifications()
	})
	return m.notifyCh
}

// relayNotifications pumps notifications from the unbounded buffer to the Go channel.
func (m *TypedTaskMgr[M]) relayNotifications() {
	defer close(m.notifyCh)
	for {
		n, ok := m.notifyBuf.Receive()
		if !ok {
			return
		}
		m.notifyCh <- n
	}
}

// HasRunning reports whether any tasks are currently in StatusRunning.
func (m *TypedTaskMgr[M]) HasRunning() bool {
	m.mu.Lock()
	defer m.mu.Unlock()

	for _, rec := range m.tasks {
		if !rec.done {
			return true
		}
	}
	return false
}

// WaitAllDone blocks until all registered tasks have reached a terminal state,
// or until the provided context is canceled.
func (m *TypedTaskMgr[M]) WaitAllDone(ctx context.Context) error {
	done := make(chan struct{})
	defer close(done)
	go func() {
		select {
		case <-ctx.Done():
			m.cond.Broadcast()
		case <-done:
		}
	}()

	m.mu.Lock()
	defer m.mu.Unlock()

	for m.hasRunningLocked() {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		m.cond.Wait()
	}
	return nil
}

// Close performs graceful shutdown.
// It waits for all running tasks to complete (up to the ctx deadline),
// then cancels any remaining running tasks.
// If Subscribe was called, the notification channel is closed after all
// pending notifications have been delivered.
// After Close returns, Run will return an error.
func (m *TypedTaskMgr[M]) Close(ctx context.Context) error {
	_ = m.WaitAllDone(ctx)

	m.mu.Lock()
	defer m.mu.Unlock()

	m.closed = true

	for _, rec := range m.tasks {
		if !rec.done {
			m.cancelTask(rec)
		}
	}

	if m.notifyBuf != nil {
		m.notifyBuf.Close()
	}

	return nil
}

// createTask registers a new task in StatusRunning state and sends a running notification.
// Returns the task ID and an event generator for forwarding agent events to the subscriber.
// The cancel function is not set here — call storeCancelFunc after creation.
func (m *TypedTaskMgr[M]) createTask(description string, background bool) (string, *adk.AsyncGenerator[*adk.TypedAgentEvent[M]], error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.closed {
		return "", nil, fmt.Errorf("subagent: task manager is closed")
	}

	m.seq++
	id := "task_" + strconv.FormatInt(m.seq, 10)

	eventIter, eventGen := adk.NewAsyncIteratorPair[*adk.TypedAgentEvent[M]]()

	rec := &typedTaskRecord[M]{
		task: Task{
			ID:              id,
			Description:     description,
			Status:          StatusRunning,
			RunInBackground: background,
			CreatedAt:       time.Now(),
		},
		eventGen: eventGen,
	}
	m.tasks[id] = rec

	m.sendNotificationLocked(&TypedNotification[M]{
		Task:   cloneTask(&rec.task),
		Events: eventIter,
	})

	return id, eventGen, nil
}

// storeCancelFunc saves the AgentCancelFunc for a running task.
// Called after createTask but before the agent starts executing,
// so that Cancel() can invoke it.
func (m *TypedTaskMgr[M]) storeCancelFunc(id string, cancel adk.AgentCancelFunc) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if rec, ok := m.tasks[id]; ok {
		rec.cancel = cancel
	}
}

// completeTask transitions a task to StatusCompleted with the given result.
// No-op if the task is already in a terminal state (idempotent).
func (m *TypedTaskMgr[M]) completeTask(id string, result string) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *typedTaskRecord[M]) {
		rec.task.Status = StatusCompleted
		rec.task.Result = result
	})
}

// failTask transitions a task to StatusFailed with the given error.
// No-op if the task is already in a terminal state (idempotent).
func (m *TypedTaskMgr[M]) failTask(id string, err error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.finalize(id, func(rec *typedTaskRecord[M]) {
		rec.task.Status = StatusFailed
		if err != nil {
			rec.task.Error = err.Error()
		}
	})
}

// cancelTask transitions a task to StatusCanceled and invokes its cancel function.
// Must be called with m.mu held.
func (m *TypedTaskMgr[M]) cancelTask(rec *typedTaskRecord[M]) {
	if rec.cancel != nil {
		rec.cancel(adk.WithAgentCancelMode(adk.CancelImmediate))
	}

	m.finalize(rec.task.ID, func(rec *typedTaskRecord[M]) {
		rec.task.Status = StatusCanceled
	})
}

// finalize applies a terminal state transition to a task.
// It sets done=true, records DoneAt, sends a notification, and broadcasts the condition.
// Returns false if the task was not found or already in a terminal state (idempotent).
// Must be called with m.mu held.
func (m *TypedTaskMgr[M]) finalize(id string, apply func(rec *typedTaskRecord[M])) bool {
	rec, ok := m.tasks[id]
	if !ok || rec.done {
		return false
	}

	rec.done = true
	now := time.Now()
	rec.task.DoneAt = &now
	apply(rec)

	// Close event generator — subscriber's Events iterator will see EOF.
	if rec.eventGen != nil {
		rec.eventGen.Close()
	}

	m.sendNotificationLocked(&TypedNotification[M]{Task: cloneTask(&rec.task)})
	m.cond.Broadcast()
	return true
}

func (m *TypedTaskMgr[M]) getAgent(name string) (adk.TypedAgent[M], bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	agent, ok := m.agents[name]
	return agent, ok
}

func (m *TypedTaskMgr[M]) hasRunningLocked() bool {
	for _, rec := range m.tasks {
		if !rec.done {
			return true
		}
	}
	return false
}

// sendNotificationLocked sends a notification to the subscriber if present.
// Uses TrySend to avoid panic if the buffer is already closed.
// Must be called with m.mu held.
func (m *TypedTaskMgr[M]) sendNotificationLocked(n *TypedNotification[M]) {
	if m.notifyBuf != nil {
		m.notifyBuf.TrySend(n)
	}
}

// drainEvents consumes all events from the iterator and returns the final message content.
// It closes intermediate MessageStreams to prevent resource leaks.
// When gen is non-nil, each event is copied and forwarded to the generator,
// enabling subscribers to stream agent events in real time.
func drainEvents[M adk.MessageType](iter *adk.AsyncIterator[*adk.TypedAgentEvent[M]], gen *adk.AsyncGenerator[*adk.TypedAgentEvent[M]]) (string, error) {
	var lastEvent *adk.TypedAgentEvent[M]
	for {
		event, ok := iter.Next()
		if !ok {
			break
		}

		// Close previous event's MessageStream to prevent leaks.
		if lastEvent != nil &&
			lastEvent.Output != nil &&
			lastEvent.Output.MessageOutput != nil &&
			lastEvent.Output.MessageOutput.MessageStream != nil {
			lastEvent.Output.MessageOutput.MessageStream.Close()
		}

		if event.Err != nil {
			return "", event.Err
		}

		// Forward event to subscriber.
		if gen != nil {
			tmp := adk.CopyTypedAgentEvent(event)
			gen.Send(event)
			event = tmp
		}

		lastEvent = event
	}

	if lastEvent == nil {
		return "", errors.New("subagent: no event returned from agent")
	}

	if lastEvent.Output != nil && lastEvent.Output.MessageOutput != nil {
		msg, _, err := adk.TypedGetMessage[M](lastEvent)
		if err != nil {
			return "", err
		}
		return extractTextContent[M](msg), nil
	}

	return "", nil
}

func cloneTask(t *Task) *Task {
	clone := *t
	return &clone
}
