/*
 * Copyright 2024 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package parent

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/cloudwego/eino/components/document"
	"github.com/cloudwego/eino/components/indexer"
	"github.com/cloudwego/eino/schema"
)

type Config struct {
	// Indexer specifies the original indexer used to create document index.
	Indexer indexer.Indexer
	// Transformer specifies the processor before creating document index, typically a splitter.
	Transformer document.Transformer
	// ParentIDKey specifies the key in the metadata of the sub-documents generated by the transformer to store the parent document ID.
	ParentIDKey string

	// SubIDGenerator specifies the method for generating a specified number of sub-document IDs based on the parent document ID. Use UUID by default.
	SubIDGenerator func(ctx context.Context, parentID string, num int) ([]string, error)
}

func NewIndexer(ctx context.Context, config *Config) (indexer.Indexer, error) {
	if config.Indexer == nil {
		return nil, fmt.Errorf("indexer is empty")
	}
	if config.Transformer == nil {
		return nil, fmt.Errorf("transformer is empty")
	}
	idGen := config.SubIDGenerator
	if idGen == nil {
		idGen = func(ctx context.Context, parentID string, num int) ([]string, error) {
			ret := make([]string, num)
			for i := 0; i < num; i++ {
				ret[i] = uuid.New().String()
			}
			return ret, nil
		}
	}

	return &parentIndexer{
		indexer:        config.Indexer,
		transformer:    config.Transformer,
		parentIDKey:    config.ParentIDKey,
		subIDGenerator: idGen,
	}, nil
}

type parentIndexer struct {
	indexer        indexer.Indexer
	transformer    document.Transformer
	parentIDKey    string
	subIDGenerator func(ctx context.Context, parentID string, num int) ([]string, error)
}

func (p *parentIndexer) Store(ctx context.Context, docs []*schema.Document, opts ...indexer.Option) ([]string, error) {
	subDocs, err := p.transformer.Transform(ctx, docs)
	if err != nil {
		return nil, err
	}
	var currentID string
	startIdx := 0
	for i, subDoc := range subDocs {
		if subDoc.MetaData == nil {
			subDoc.MetaData = make(map[string]interface{})
		}
		subDoc.MetaData[p.parentIDKey] = subDoc.ID

		if subDoc.ID == currentID {
			continue
		}

		// generate new doc id
		subIDs, err := p.subIDGenerator(ctx, subDocs[startIdx].ID, i-startIdx)
		if err != nil {
			return nil, err
		}
		if len(subIDs) != i-startIdx {
			return nil, fmt.Errorf("generated sub IDs' num is unexpected")
		}
		for j := startIdx; j < i; j++ {
			subDocs[j].ID = subIDs[j-startIdx]
		}
		startIdx = i
		currentID = subDoc.ID
	}
	// generate new doc id
	subIDs, err := p.subIDGenerator(ctx, subDocs[startIdx].ID, len(subDocs)-startIdx)
	if err != nil {
		return nil, err
	}
	if len(subIDs) != len(subDocs)-startIdx {
		return nil, fmt.Errorf("generated sub IDs' num is unexpected")
	}
	for j := startIdx; j < len(subDocs); j++ {
		subDocs[j].ID = subIDs[j-startIdx]
	}

	return p.indexer.Store(ctx, subDocs, opts...)
}
